export const POPULAR_LOCATIONS = [
  {
    id: "1",
    name: "KLCC",
    fullName: "KLCC - Petronas Twin Towers",
    address: "Petronas Twin Towers, Kuala Lumpur City Centre, Kuala Lumpur",
    latitude: 3.1579,
    longitude: 101.7116,
  },
  {
    id: "2",
    name: "Pavilion KL",
    fullName: "Pavilion Kuala Lumpur",
    address: "Pavilion Kuala Lumpur, Bukit Bintang, Kuala Lumpur",
    latitude: 3.1493,
    longitude: 101.7142,
  },
  {
    id: "3",
    name: "Batu Caves",
    fullName: "Batu Caves Temple",
    address: "Batu Caves, Gombak, Selangor",
    latitude: 3.2379,
    longitude: 101.6840,
  },
  {
    id: "4",
    name: "KL Sentral",
    fullName: "KL Sentral Station",
    address: "KL Sentral Station, Kuala Lumpur",
    latitude: 3.1345,
    longitude: 101.6869,
  },
  {
    id: "5",
    name: "Mid Valley",
    fullName: "Mid Valley Megamall",
    address: "Mid Valley City, Kuala Lumpur",
    latitude: 3.1184,
    longitude: 101.6774,
  },
  {
    id: "6",
    name: "Bukit Bintang",
    fullName: "Bukit Bintang",
    address: "Jalan Bukit Bintang, Kuala Lumpur",
    latitude: 3.1478,
    longitude: 101.7123,
  },
  {
    id: "7",
    name: "KLIA",
    fullName: "Kuala Lumpur International Airport (KLIA)",
    address: "Kuala Lumpur International Airport, Sepang, Selangor",
    latitude: 2.7456,
    longitude: 101.7072,
  },
  {
    id: "8",
    name: "Sunway Pyramid",
    fullName: "Sunway Pyramid Shopping Mall",
    address: "Sunway Pyramid Shopping Mall, Bandar Sunway, Selangor",
    latitude: 3.0733,
    longitude: 101.6069,
  },
  {
    id: "9",
    name: "The Curve",
    fullName: "The Curve Shopping Mall",
    address: "The Curve Shopping Mall, Mutiara Damansara, Selangor",
    latitude: 3.1533,
    longitude: 101.6105,
  },
  {
    id: "10",
    name: "1 Utama",
    fullName: "1 Utama Shopping Centre",
    address: "1 Utama Shopping Centre, Bandar Utama, Selangor",
    latitude: 3.1506,
    longitude: 101.6147,
  },
];
