/**
 * Comprehensive vehicle catalog seed used by admin-settings-vehicle-make-model.
 * Hierarchy: vehicleType -> energyType -> make -> model + year range.
 *
 * Intense, deeply detailed dataset spanning passenger cars, SUVs, MPVs,
 * pick-ups, vans, trucks, buses, motorcycles, scooters, auto-rickshaws,
 * coupes/convertibles, station wagons, and micro/kei cars across
 * petrol, diesel, hybrid, PHEV, EV, CNG and hydrogen energy types.
 */

export interface VehicleCatalogRow {
  vehicleType: string;
  energyType: string;
  make: string;
  model: string;
  yearFrom: string;
  /** Empty string + ongoing flag is encoded as yearTo = "~" at persistence time. */
  yearTo: string;
}

type R = VehicleCatalogRow;

const r = (
  vehicleType: string,
  energyType: string,
  make: string,
  model: string,
  yearFrom: string,
  yearTo: string,
): R => ({ vehicleType, energyType, make, model, yearFrom, yearTo });

// ---------------- SEDAN ----------------
const SEDAN: R[] = [
  // Proton
  r("Sedan", "Petrol", "Proton", "Saga", "1985", "~"),
  r("Sedan", "Petrol", "Proton", "Wira", "1993", "2009"),
  r("Sedan", "Petrol", "Proton", "Waja", "2000", "2011"),
  r("Sedan", "Petrol", "Proton", "Persona", "2007", "~"),
  r("Sedan", "Petrol", "Proton", "Inspira", "2010", "2015"),
  r("Sedan", "Petrol", "Proton", "Preve", "2012", "2020"),
  r("Sedan", "Petrol", "Proton", "Perdana", "1995", "2020"),
  r("Sedan", "Petrol", "Proton", "S70", "2024", "~"),
  r("Sedan", "Petrol", "Proton", "Iswara", "1992", "2003"),
  r("Sedan", "Petrol", "Proton", "Tiara", "1996", "2000"),
  r("Sedan", "Petrol", "Proton", "Gen-2 Sedan", "2008", "2012"),
  // Perodua
  r("Sedan", "Petrol", "Perodua", "Bezza", "2016", "~"),
  // Toyota
  r("Sedan", "Petrol", "Toyota", "Vios", "2003", "~"),
  r("Sedan", "Petrol", "Toyota", "Yaris Sedan", "2017", "~"),
  r("Sedan", "Petrol", "Toyota", "Corolla Altis", "2001", "~"),
  r("Sedan", "Hybrid", "Toyota", "Corolla Altis Hybrid", "2019", "~"),
  r("Sedan", "Petrol", "Toyota", "Camry", "1982", "~"),
  r("Sedan", "Hybrid", "Toyota", "Camry Hybrid", "2011", "~"),
  r("Sedan", "Hybrid", "Toyota", "Prius", "1997", "~"),
  r("Sedan", "PHEV", "Toyota", "Prius Prime", "2017", "~"),
  r("Sedan", "Hydrogen", "Toyota", "Mirai", "2014", "~"),
  r("Sedan", "Petrol", "Toyota", "Avensis", "1997", "2018"),
  r("Sedan", "Petrol", "Toyota", "Crown", "1955", "~"),
  r("Sedan", "Hybrid", "Toyota", "Crown Hybrid", "2008", "~"),
  r("Sedan", "Petrol", "Toyota", "Mark X", "2004", "2019"),
  // Honda
  r("Sedan", "Petrol", "Honda", "City", "1996", "~"),
  r("Sedan", "Hybrid", "Honda", "City e:HEV", "2021", "~"),
  r("Sedan", "Petrol", "Honda", "Civic", "1972", "~"),
  r("Sedan", "Hybrid", "Honda", "Civic e:HEV", "2022", "~"),
  r("Sedan", "Petrol", "Honda", "Civic Type R", "1997", "~"),
  r("Sedan", "Petrol", "Honda", "Accord", "1976", "~"),
  r("Sedan", "Hybrid", "Honda", "Accord Hybrid", "2014", "~"),
  r("Sedan", "Petrol", "Honda", "Legend", "1985", "2021"),
  // Nissan
  r("Sedan", "Petrol", "Nissan", "Almera", "1995", "~"),
  r("Sedan", "Petrol", "Nissan", "Sentra", "1982", "~"),
  r("Sedan", "Petrol", "Nissan", "Sylphy", "2000", "~"),
  r("Sedan", "Petrol", "Nissan", "Teana", "2003", "2020"),
  r("Sedan", "Petrol", "Nissan", "Skyline", "1957", "~"),
  r("Sedan", "Petrol", "Nissan", "Maxima", "1981", "2023"),
  r("Sedan", "Petrol", "Nissan", "Cefiro", "1988", "2003"),
  // Mazda
  r("Sedan", "Petrol", "Mazda", "2 Sedan", "2007", "~"),
  r("Sedan", "Petrol", "Mazda", "3 Sedan", "2003", "~"),
  r("Sedan", "Petrol", "Mazda", "6", "2002", "~"),
  // Hyundai
  r("Sedan", "Petrol", "Hyundai", "Accent", "1994", "~"),
  r("Sedan", "Petrol", "Hyundai", "Avante", "1990", "~"),
  r("Sedan", "Petrol", "Hyundai", "Elantra", "1990", "~"),
  r("Sedan", "Petrol", "Hyundai", "Sonata", "1985", "~"),
  r("Sedan", "Hybrid", "Hyundai", "Sonata Hybrid", "2011", "~"),
  r("Sedan", "Petrol", "Hyundai", "Genesis", "2008", "2016"),
  r("Sedan", "EV", "Hyundai", "Ioniq Electric", "2016", "2022"),
  // Kia
  r("Sedan", "Petrol", "Kia", "Cerato", "2003", "~"),
  r("Sedan", "Petrol", "Kia", "Forte", "2008", "~"),
  r("Sedan", "Petrol", "Kia", "Optima K5", "2000", "~"),
  r("Sedan", "Hybrid", "Kia", "Optima Hybrid", "2011", "~"),
  r("Sedan", "Petrol", "Kia", "Stinger", "2017", "2023"),
  // BMW
  r("Sedan", "Petrol", "BMW", "318i", "1990", "~"),
  r("Sedan", "Petrol", "BMW", "320i", "1975", "~"),
  r("Sedan", "Petrol", "BMW", "330i", "1992", "~"),
  r("Sedan", "Diesel", "BMW", "320d", "1998", "~"),
  r("Sedan", "Diesel", "BMW", "330d", "1999", "~"),
  r("Sedan", "Petrol", "BMW", "520i", "1981", "~"),
  r("Sedan", "Petrol", "BMW", "530i", "1992", "~"),
  r("Sedan", "Diesel", "BMW", "530d", "1999", "~"),
  r("Sedan", "PHEV", "BMW", "530e", "2017", "~"),
  r("Sedan", "Petrol", "BMW", "540i", "1997", "~"),
  r("Sedan", "Petrol", "BMW", "740i", "1992", "~"),
  r("Sedan", "PHEV", "BMW", "745e", "2019", "2022"),
  r("Sedan", "Petrol", "BMW", "750i", "1987", "~"),
  r("Sedan", "Petrol", "BMW", "760Li", "2002", "~"),
  r("Sedan", "EV", "BMW", "i4", "2021", "~"),
  r("Sedan", "EV", "BMW", "i5", "2023", "~"),
  r("Sedan", "EV", "BMW", "i7", "2022", "~"),
  r("Sedan", "Petrol", "BMW", "M3", "1986", "~"),
  r("Sedan", "Petrol", "BMW", "M5", "1985", "~"),
  r("Sedan", "Petrol", "BMW", "M340i", "2019", "~"),
  r("Sedan", "Petrol", "BMW", "M760Li", "2017", "~"),
  // Mercedes-Benz
  r("Sedan", "Petrol", "Mercedes-Benz", "A-Class Sedan", "2018", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "C180", "1993", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "C200", "1993", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "C300", "2014", "~"),
  r("Sedan", "Diesel", "Mercedes-Benz", "C220d", "1993", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "C43 AMG", "2015", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "C63 AMG", "2008", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "E200", "1985", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "E300", "1985", "~"),
  r("Sedan", "Diesel", "Mercedes-Benz", "E220d", "2016", "~"),
  r("Sedan", "PHEV", "Mercedes-Benz", "E300e", "2019", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "E450", "2018", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "E63 AMG", "2007", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "S350", "2005", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "S450", "2017", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "S500", "1992", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "S560", "2017", "2020"),
  r("Sedan", "Petrol", "Mercedes-Benz", "S580", "2020", "~"),
  r("Sedan", "Petrol", "Mercedes-Benz", "S680 Maybach", "2021", "~"),
  r("Sedan", "EV", "Mercedes-Benz", "EQE", "2022", "~"),
  r("Sedan", "EV", "Mercedes-Benz", "EQS", "2021", "~"),
  // Audi
  r("Sedan", "Petrol", "Audi", "A3 Sedan", "2013", "~"),
  r("Sedan", "Petrol", "Audi", "A4", "1994", "~"),
  r("Sedan", "Diesel", "Audi", "A4 TDI", "1995", "~"),
  r("Sedan", "Petrol", "Audi", "A5 Sedan", "2007", "~"),
  r("Sedan", "Petrol", "Audi", "A6", "1994", "~"),
  r("Sedan", "Diesel", "Audi", "A6 TDI", "1995", "~"),
  r("Sedan", "Petrol", "Audi", "A7", "2010", "~"),
  r("Sedan", "Petrol", "Audi", "A8", "1994", "~"),
  r("Sedan", "EV", "Audi", "e-tron GT", "2021", "~"),
  r("Sedan", "Petrol", "Audi", "S4", "1991", "~"),
  r("Sedan", "Petrol", "Audi", "S6", "1994", "~"),
  r("Sedan", "Petrol", "Audi", "RS3 Sedan", "2017", "~"),
  r("Sedan", "Petrol", "Audi", "RS5", "2017", "~"),
  r("Sedan", "Petrol", "Audi", "RS6", "2002", "~"),
  r("Sedan", "Petrol", "Audi", "RS7", "2013", "~"),
  // Lexus
  r("Sedan", "Petrol", "Lexus", "IS200t", "2015", "~"),
  r("Sedan", "Petrol", "Lexus", "IS300", "1999", "~"),
  r("Sedan", "Petrol", "Lexus", "IS350", "2005", "~"),
  r("Sedan", "Petrol", "Lexus", "IS500 F Sport", "2021", "~"),
  r("Sedan", "Petrol", "Lexus", "ES250", "2018", "~"),
  r("Sedan", "Hybrid", "Lexus", "ES300h", "2012", "~"),
  r("Sedan", "Petrol", "Lexus", "ES350", "1989", "~"),
  r("Sedan", "Petrol", "Lexus", "GS350", "1993", "2020"),
  r("Sedan", "Petrol", "Lexus", "LS460", "2006", "~"),
  r("Sedan", "Petrol", "Lexus", "LS500", "2017", "~"),
  r("Sedan", "Hybrid", "Lexus", "LS500h", "2017", "~"),
  // Porsche / VW / Volvo
  r("Sedan", "Petrol", "Porsche", "Panamera", "2009", "~"),
  r("Sedan", "PHEV", "Porsche", "Panamera E-Hybrid", "2013", "~"),
  r("Sedan", "EV", "Porsche", "Taycan", "2019", "~"),
  r("Sedan", "Petrol", "Volkswagen", "Passat", "1973", "~"),
  r("Sedan", "Diesel", "Volkswagen", "Passat TDI", "1996", "~"),
  r("Sedan", "Petrol", "Volkswagen", "Jetta", "1979", "~"),
  r("Sedan", "Petrol", "Volkswagen", "Arteon", "2017", "~"),
  r("Sedan", "Petrol", "Volkswagen", "Vento", "1992", "~"),
  r("Sedan", "Petrol", "Volvo", "S60", "2000", "~"),
  r("Sedan", "PHEV", "Volvo", "S60 T8", "2016", "~"),
  r("Sedan", "Petrol", "Volvo", "S90", "2016", "~"),
  r("Sedan", "PHEV", "Volvo", "S90 T8", "2016", "~"),
  // Tesla / BYD / NIO / Xpeng / Lucid / MG / Zeekr / Polestar
  r("Sedan", "EV", "Tesla", "Model 3", "2017", "~"),
  r("Sedan", "EV", "Tesla", "Model 3 Performance", "2018", "~"),
  r("Sedan", "EV", "Tesla", "Model S", "2012", "~"),
  r("Sedan", "EV", "Tesla", "Model S Plaid", "2021", "~"),
  r("Sedan", "EV", "BYD", "Seal", "2022", "~"),
  r("Sedan", "EV", "BYD", "Han", "2020", "~"),
  r("Sedan", "PHEV", "BYD", "Han DM-i", "2021", "~"),
  r("Sedan", "EV", "NIO", "ET5", "2022", "~"),
  r("Sedan", "EV", "NIO", "ET7", "2022", "~"),
  r("Sedan", "EV", "NIO", "ET9", "2024", "~"),
  r("Sedan", "EV", "Xpeng", "P5", "2021", "~"),
  r("Sedan", "EV", "Xpeng", "P7", "2020", "~"),
  r("Sedan", "EV", "Xpeng", "P7+", "2024", "~"),
  r("Sedan", "EV", "Lucid", "Air", "2021", "~"),
  r("Sedan", "EV", "MG", "MG5", "2020", "~"),
  r("Sedan", "EV", "MG", "MG7", "2022", "~"),
  r("Sedan", "EV", "Zeekr", "001", "2021", "~"),
  r("Sedan", "EV", "Zeekr", "007", "2024", "~"),
  r("Sedan", "EV", "Polestar", "2", "2019", "~"),
  r("Sedan", "EV", "Polestar", "5", "2025", "~"),
  // Genesis
  r("Sedan", "Petrol", "Genesis", "G70", "2017", "~"),
  r("Sedan", "Petrol", "Genesis", "G80", "2016", "~"),
  r("Sedan", "EV", "Genesis", "G80 Electrified", "2021", "~"),
  r("Sedan", "Petrol", "Genesis", "G90", "2015", "~"),
  // Cadillac / Chrysler / Bentley / Rolls-Royce / Maserati / Jaguar
  r("Sedan", "Petrol", "Cadillac", "CT4", "2019", "~"),
  r("Sedan", "Petrol", "Cadillac", "CT5", "2019", "~"),
  r("Sedan", "Petrol", "Cadillac", "CT6", "2015", "2020"),
  r("Sedan", "Petrol", "Chrysler", "300", "2004", "~"),
  r("Sedan", "Petrol", "Bentley", "Flying Spur", "2005", "~"),
  r("Sedan", "Petrol", "Rolls-Royce", "Ghost", "2009", "~"),
  r("Sedan", "Petrol", "Rolls-Royce", "Phantom", "2003", "~"),
  r("Sedan", "EV", "Rolls-Royce", "Spectre", "2024", "~"),
  r("Sedan", "Petrol", "Maserati", "Ghibli", "2013", "~"),
  r("Sedan", "Petrol", "Maserati", "Quattroporte", "2003", "~"),
  r("Sedan", "Petrol", "Jaguar", "XE", "2014", "~"),
  r("Sedan", "Petrol", "Jaguar", "XF", "2007", "~"),
  r("Sedan", "Petrol", "Jaguar", "XJ", "1968", "2019"),
];

// ---------------- HATCHBACK ----------------
const HATCHBACK: R[] = [
  r("Hatchback", "Petrol", "Perodua", "Myvi", "2005", "~"),
  r("Hatchback", "Petrol", "Perodua", "Axia", "2014", "~"),
  r("Hatchback", "Petrol", "Perodua", "Viva", "2007", "2014"),
  r("Hatchback", "Petrol", "Perodua", "Kancil", "1994", "2009"),
  r("Hatchback", "Petrol", "Perodua", "Kelisa", "2001", "2007"),
  r("Hatchback", "Petrol", "Proton", "Iriz", "2014", "~"),
  r("Hatchback", "Petrol", "Proton", "Satria", "1994", "2015"),
  r("Hatchback", "Petrol", "Proton", "Satria Neo", "2006", "2015"),
  r("Hatchback", "Petrol", "Proton", "Savvy", "2005", "2011"),
  r("Hatchback", "Petrol", "Toyota", "Yaris", "1999", "~"),
  r("Hatchback", "Petrol", "Toyota", "Aygo", "2005", "~"),
  r("Hatchback", "Hybrid", "Toyota", "Yaris Hybrid", "2012", "~"),
  r("Hatchback", "Petrol", "Honda", "Jazz", "2001", "2020"),
  r("Hatchback", "Hybrid", "Honda", "Jazz Hybrid", "2010", "2020"),
  r("Hatchback", "Hybrid", "Honda", "Fit e:HEV", "2020", "~"),
  r("Hatchback", "Petrol", "Mazda", "2 Hatchback", "2007", "~"),
  r("Hatchback", "Petrol", "Mazda", "3 Hatchback", "2003", "~"),
  r("Hatchback", "Petrol", "Volkswagen", "Polo", "1975", "~"),
  r("Hatchback", "Petrol", "Volkswagen", "Up!", "2011", "~"),
  r("Hatchback", "Petrol", "Volkswagen", "Golf", "1974", "~"),
  r("Hatchback", "Petrol", "Volkswagen", "Golf GTI", "1976", "~"),
  r("Hatchback", "Petrol", "Volkswagen", "Golf R", "2002", "~"),
  r("Hatchback", "Diesel", "Volkswagen", "Golf TDI", "1991", "~"),
  r("Hatchback", "Petrol", "Mini", "Cooper", "2001", "~"),
  r("Hatchback", "Petrol", "Mini", "Cooper S", "2001", "~"),
  r("Hatchback", "Petrol", "Mini", "JCW", "2007", "~"),
  r("Hatchback", "EV", "Mini", "Cooper SE", "2020", "~"),
  r("Hatchback", "Petrol", "Suzuki", "Swift", "2004", "~"),
  r("Hatchback", "Hybrid", "Suzuki", "Swift Hybrid", "2017", "~"),
  r("Hatchback", "Petrol", "Suzuki", "Baleno", "2015", "~"),
  r("Hatchback", "Petrol", "Suzuki", "Celerio", "2014", "~"),
  r("Hatchback", "Petrol", "Suzuki", "Alto", "1979", "~"),
  r("Hatchback", "Petrol", "Hyundai", "i10", "2007", "~"),
  r("Hatchback", "Petrol", "Hyundai", "i20", "2008", "~"),
  r("Hatchback", "Petrol", "Hyundai", "i30", "2007", "~"),
  r("Hatchback", "Petrol", "Hyundai", "i30 N", "2017", "~"),
  r("Hatchback", "Petrol", "Kia", "Picanto", "2004", "~"),
  r("Hatchback", "Petrol", "Kia", "Rio", "1999", "~"),
  r("Hatchback", "Petrol", "Kia", "Ceed", "2006", "~"),
  r("Hatchback", "Petrol", "Ford", "Fiesta", "1976", "~"),
  r("Hatchback", "Petrol", "Ford", "Fiesta ST", "2002", "~"),
  r("Hatchback", "Petrol", "Ford", "Focus", "1998", "~"),
  r("Hatchback", "Petrol", "Ford", "Focus ST", "2002", "~"),
  r("Hatchback", "Petrol", "Ford", "Focus RS", "2002", "2018"),
  r("Hatchback", "Petrol", "Renault", "Clio", "1990", "~"),
  r("Hatchback", "Petrol", "Renault", "Megane", "1995", "~"),
  r("Hatchback", "EV", "Renault", "Zoe", "2012", "~"),
  r("Hatchback", "EV", "Renault", "Megane E-Tech", "2022", "~"),
  r("Hatchback", "Petrol", "Peugeot", "208", "2012", "~"),
  r("Hatchback", "EV", "Peugeot", "e-208", "2019", "~"),
  r("Hatchback", "Petrol", "Peugeot", "308", "2007", "~"),
  r("Hatchback", "Petrol", "Citroen", "C3", "2002", "~"),
  r("Hatchback", "Petrol", "Citroen", "C4", "2004", "~"),
  r("Hatchback", "Petrol", "Fiat", "500", "2007", "~"),
  r("Hatchback", "EV", "Fiat", "500e", "2020", "~"),
  r("Hatchback", "Petrol", "Fiat", "Panda", "1980", "~"),
  r("Hatchback", "EV", "BMW", "i3", "2013", "2022"),
  r("Hatchback", "Petrol", "BMW", "1 Series", "2004", "~"),
  r("Hatchback", "Petrol", "Mercedes-Benz", "A-Class", "1997", "~"),
  r("Hatchback", "Petrol", "Mercedes-Benz", "A45 AMG", "2013", "~"),
  r("Hatchback", "EV", "Volkswagen", "ID.3", "2020", "~"),
  r("Hatchback", "EV", "BYD", "Dolphin", "2021", "~"),
  r("Hatchback", "EV", "BYD", "Seagull", "2023", "~"),
  r("Hatchback", "EV", "Ora", "Good Cat", "2020", "~"),
  r("Hatchback", "EV", "Ora", "Lightning Cat", "2022", "~"),
  r("Hatchback", "EV", "MG", "MG4", "2022", "~"),
  r("Hatchback", "EV", "MG", "Mulan", "2022", "~"),
  r("Hatchback", "Petrol", "Subaru", "Impreza", "1992", "~"),
  r("Hatchback", "Petrol", "Subaru", "WRX", "1992", "~"),
];

// ---------------- COUPE ----------------
const COUPE: R[] = [
  r("Coupe", "Petrol", "BMW", "M2", "2015", "~"),
  r("Coupe", "Petrol", "BMW", "M4", "2014", "~"),
  r("Coupe", "Petrol", "BMW", "M8", "2018", "~"),
  r("Coupe", "Petrol", "BMW", "8 Series", "2018", "~"),
  r("Coupe", "Petrol", "BMW", "Z4", "2002", "~"),
  r("Coupe", "Petrol", "Mercedes-Benz", "C-Class Coupe", "2011", "~"),
  r("Coupe", "Petrol", "Mercedes-Benz", "E-Class Coupe", "2009", "~"),
  r("Coupe", "Petrol", "Mercedes-Benz", "AMG GT", "2014", "~"),
  r("Coupe", "Petrol", "Mercedes-Benz", "AMG GT 63", "2018", "~"),
  r("Coupe", "Petrol", "Mercedes-Benz", "SL", "1954", "~"),
  r("Coupe", "Petrol", "Audi", "TT", "1998", "2023"),
  r("Coupe", "Petrol", "Audi", "R8", "2006", "2024"),
  r("Coupe", "Petrol", "Audi", "RS5 Coupe", "2010", "~"),
  r("Coupe", "Petrol", "Porsche", "911 Carrera", "1963", "~"),
  r("Coupe", "Petrol", "Porsche", "911 Turbo", "1974", "~"),
  r("Coupe", "Petrol", "Porsche", "911 GT3", "1999", "~"),
  r("Coupe", "Petrol", "Porsche", "911 GT3 RS", "2003", "~"),
  r("Coupe", "Petrol", "Porsche", "718 Cayman", "2016", "~"),
  r("Coupe", "Petrol", "Porsche", "718 Boxster", "2016", "~"),
  r("Coupe", "Petrol", "Nissan", "GT-R", "2007", "~"),
  r("Coupe", "Petrol", "Nissan", "GT-R Nismo", "2014", "~"),
  r("Coupe", "Petrol", "Nissan", "Z", "2022", "~"),
  r("Coupe", "Petrol", "Nissan", "370Z", "2008", "2020"),
  r("Coupe", "Petrol", "Nissan", "350Z", "2002", "2008"),
  r("Coupe", "Petrol", "Toyota", "Supra", "1978", "~"),
  r("Coupe", "Petrol", "Toyota", "GR86", "2021", "~"),
  r("Coupe", "Petrol", "Subaru", "BRZ", "2012", "~"),
  r("Coupe", "Petrol", "Mazda", "MX-5 Miata", "1989", "~"),
  r("Coupe", "Petrol", "Mazda", "RX-7", "1978", "2002"),
  r("Coupe", "Petrol", "Mazda", "RX-8", "2003", "2012"),
  r("Coupe", "Petrol", "Honda", "S2000", "1999", "2009"),
  r("Coupe", "Petrol", "Honda", "NSX", "1990", "2022"),
  r("Coupe", "Petrol", "Lexus", "LC500", "2017", "~"),
  r("Coupe", "Hybrid", "Lexus", "LC500h", "2017", "~"),
  r("Coupe", "Petrol", "Lexus", "RC F", "2014", "~"),
  r("Coupe", "Petrol", "Chevrolet", "Corvette C7", "2014", "2019"),
  r("Coupe", "Petrol", "Chevrolet", "Corvette C8", "2020", "~"),
  r("Coupe", "Petrol", "Chevrolet", "Camaro", "1966", "2024"),
  r("Coupe", "Petrol", "Chevrolet", "Camaro ZL1", "2012", "2024"),
  r("Coupe", "Petrol", "Ford", "Mustang", "1964", "~"),
  r("Coupe", "Petrol", "Ford", "Mustang GT", "1964", "~"),
  r("Coupe", "Petrol", "Ford", "Mustang Shelby GT500", "2007", "~"),
  r("Coupe", "Petrol", "Dodge", "Challenger", "2008", "2023"),
  r("Coupe", "Petrol", "Dodge", "Challenger Hellcat", "2014", "2023"),
  r("Coupe", "Petrol", "Dodge", "Charger SRT", "2006", "2023"),
  r("Coupe", "Petrol", "Aston Martin", "Vantage", "2005", "~"),
  r("Coupe", "Petrol", "Aston Martin", "DB11", "2016", "2023"),
  r("Coupe", "Petrol", "Aston Martin", "DB12", "2023", "~"),
  r("Coupe", "Petrol", "Aston Martin", "DBS Superleggera", "2018", "~"),
  r("Coupe", "Petrol", "Bentley", "Continental GT", "2003", "~"),
  r("Coupe", "Petrol", "Ferrari", "488 GTB", "2015", "2019"),
  r("Coupe", "Petrol", "Ferrari", "F8 Tributo", "2019", "~"),
  r("Coupe", "Petrol", "Ferrari", "296 GTB", "2021", "~"),
  r("Coupe", "Petrol", "Ferrari", "SF90 Stradale", "2020", "~"),
  r("Coupe", "Petrol", "Ferrari", "812 Superfast", "2017", "~"),
  r("Coupe", "Petrol", "Ferrari", "Roma", "2020", "~"),
  r("Coupe", "Petrol", "Lamborghini", "Huracan", "2014", "~"),
  r("Coupe", "Petrol", "Lamborghini", "Huracan STO", "2020", "~"),
  r("Coupe", "Petrol", "Lamborghini", "Aventador", "2011", "2022"),
  r("Coupe", "Petrol", "Lamborghini", "Revuelto", "2023", "~"),
  r("Coupe", "Petrol", "McLaren", "720S", "2017", "~"),
  r("Coupe", "Petrol", "McLaren", "765LT", "2020", "~"),
  r("Coupe", "Petrol", "McLaren", "Artura", "2021", "~"),
  r("Coupe", "Petrol", "McLaren", "GT", "2019", "~"),
  r("Coupe", "Petrol", "Maserati", "MC20", "2020", "~"),
  r("Coupe", "Petrol", "Maserati", "GranTurismo", "2007", "~"),
  r("Coupe", "EV", "Maserati", "GranTurismo Folgore", "2023", "~"),
];

// ---------------- CONVERTIBLE ----------------
const CONVERTIBLE: R[] = [
  r("Convertible", "Petrol", "Mazda", "MX-5 Miata Convertible", "1989", "~"),
  r("Convertible", "Petrol", "BMW", "M4 Convertible", "2014", "~"),
  r("Convertible", "Petrol", "BMW", "Z4 Roadster", "2002", "~"),
  r("Convertible", "Petrol", "Mercedes-Benz", "SLC", "2016", "2020"),
  r("Convertible", "Petrol", "Mercedes-Benz", "SL Roadster", "1954", "~"),
  r("Convertible", "Petrol", "Mercedes-Benz", "C-Class Cabriolet", "2016", "2023"),
  r("Convertible", "Petrol", "Mercedes-Benz", "E-Class Cabriolet", "2010", "~"),
  r("Convertible", "Petrol", "Audi", "A5 Cabriolet", "2009", "~"),
  r("Convertible", "Petrol", "Audi", "TT Roadster", "1999", "2023"),
  r("Convertible", "Petrol", "Porsche", "911 Cabriolet", "1982", "~"),
  r("Convertible", "Petrol", "Porsche", "911 Targa", "1965", "~"),
  r("Convertible", "Petrol", "Porsche", "718 Boxster Spyder", "2019", "~"),
  r("Convertible", "Petrol", "Mini", "Cooper Convertible", "2004", "~"),
  r("Convertible", "Petrol", "Ford", "Mustang Convertible", "1964", "~"),
  r("Convertible", "Petrol", "Chevrolet", "Corvette Convertible", "1953", "~"),
  r("Convertible", "Petrol", "Bentley", "Continental GTC", "2006", "~"),
  r("Convertible", "Petrol", "Rolls-Royce", "Dawn", "2015", "2023"),
  r("Convertible", "Petrol", "Aston Martin", "Vantage Roadster", "2020", "~"),
  r("Convertible", "Petrol", "Ferrari", "Portofino", "2017", "~"),
  r("Convertible", "Petrol", "Ferrari", "Roma Spider", "2023", "~"),
  r("Convertible", "Petrol", "Ferrari", "F8 Spider", "2019", "~"),
  r("Convertible", "Petrol", "Lamborghini", "Huracan Spyder", "2015", "~"),
  r("Convertible", "Petrol", "Lamborghini", "Aventador Roadster", "2012", "2022"),
  r("Convertible", "Petrol", "McLaren", "720S Spider", "2018", "~"),
  r("Convertible", "Petrol", "McLaren", "Artura Spider", "2024", "~"),
  r("Convertible", "Petrol", "Jaguar", "F-Type Convertible", "2013", "~"),
];

// ---------------- WAGON / ESTATE ----------------
const WAGON: R[] = [
  r("Wagon", "Petrol", "Volvo", "V60", "2010", "~"),
  r("Wagon", "PHEV", "Volvo", "V60 T8", "2018", "~"),
  r("Wagon", "Petrol", "Volvo", "V90", "2016", "~"),
  r("Wagon", "Petrol", "Volvo", "V90 Cross Country", "2017", "~"),
  r("Wagon", "Petrol", "Volvo", "V70", "1996", "2016"),
  r("Wagon", "Petrol", "Volvo", "850 Estate", "1991", "1997"),
  r("Wagon", "Petrol", "BMW", "3 Series Touring", "1987", "~"),
  r("Wagon", "Petrol", "BMW", "5 Series Touring", "1991", "~"),
  r("Wagon", "Petrol", "BMW", "M3 Touring", "2022", "~"),
  r("Wagon", "Petrol", "Mercedes-Benz", "C-Class Estate", "1996", "~"),
  r("Wagon", "Petrol", "Mercedes-Benz", "E-Class Estate", "1985", "~"),
  r("Wagon", "Petrol", "Mercedes-Benz", "E63 AMG Estate", "2007", "~"),
  r("Wagon", "Petrol", "Audi", "A4 Avant", "1995", "~"),
  r("Wagon", "Petrol", "Audi", "A6 Avant", "1995", "~"),
  r("Wagon", "Petrol", "Audi", "RS4 Avant", "1999", "~"),
  r("Wagon", "Petrol", "Audi", "RS6 Avant", "2002", "~"),
  r("Wagon", "Petrol", "Subaru", "Levorg", "2014", "~"),
  r("Wagon", "Petrol", "Subaru", "Legacy Wagon", "1989", "2014"),
  r("Wagon", "Petrol", "Volkswagen", "Passat Variant", "1981", "~"),
  r("Wagon", "Petrol", "Volkswagen", "Golf Variant", "1993", "~"),
  r("Wagon", "Petrol", "Skoda", "Octavia Combi", "1996", "~"),
  r("Wagon", "Petrol", "Skoda", "Superb Combi", "2009", "~"),
  r("Wagon", "Petrol", "Peugeot", "508 SW", "2010", "~"),
];

// ---------------- SUV ----------------
const SUV: R[] = [
  // Proton / Perodua
  r("SUV", "Petrol", "Proton", "X50", "2020", "~"),
  r("SUV", "Petrol", "Proton", "X70", "2018", "~"),
  r("SUV", "Petrol", "Proton", "X90", "2023", "~"),
  r("SUV", "EV", "Proton", "e.MAS 7", "2024", "~"),
  r("SUV", "Petrol", "Perodua", "Aruz", "2019", "~"),
  r("SUV", "Petrol", "Perodua", "Ativa", "2021", "~"),
  r("SUV", "Petrol", "Perodua", "Kembara", "1998", "2008"),
  r("SUV", "Petrol", "Perodua", "Nautica", "2008", "2009"),
  // Toyota
  r("SUV", "Petrol", "Toyota", "Raize", "2019", "~"),
  r("SUV", "Petrol", "Toyota", "Rush", "2006", "~"),
  r("SUV", "Petrol", "Toyota", "Corolla Cross", "2020", "~"),
  r("SUV", "Hybrid", "Toyota", "Corolla Cross Hybrid", "2020", "~"),
  r("SUV", "Petrol", "Toyota", "C-HR", "2016", "~"),
  r("SUV", "Hybrid", "Toyota", "C-HR Hybrid", "2016", "~"),
  r("SUV", "Petrol", "Toyota", "RAV4", "1994", "~"),
  r("SUV", "Hybrid", "Toyota", "RAV4 Hybrid", "2015", "~"),
  r("SUV", "PHEV", "Toyota", "RAV4 PHEV", "2020", "~"),
  r("SUV", "Petrol", "Toyota", "Harrier", "1997", "~"),
  r("SUV", "Hybrid", "Toyota", "Harrier Hybrid", "2005", "~"),
  r("SUV", "Petrol", "Toyota", "Fortuner", "2004", "~"),
  r("SUV", "Diesel", "Toyota", "Fortuner Diesel", "2004", "~"),
  r("SUV", "Petrol", "Toyota", "Land Cruiser", "1951", "~"),
  r("SUV", "Diesel", "Toyota", "Land Cruiser Diesel", "1951", "~"),
  r("SUV", "Petrol", "Toyota", "Land Cruiser Prado", "1990", "~"),
  r("SUV", "Diesel", "Toyota", "Land Cruiser Prado Diesel", "1990", "~"),
  r("SUV", "Hybrid", "Toyota", "Highlander Hybrid", "2005", "~"),
  r("SUV", "Hybrid", "Toyota", "Kluger Hybrid", "2000", "~"),
  r("SUV", "EV", "Toyota", "bZ4X", "2022", "~"),
  // Honda
  r("SUV", "Petrol", "Honda", "HR-V", "1998", "~"),
  r("SUV", "Hybrid", "Honda", "HR-V Hybrid", "2021", "~"),
  r("SUV", "Petrol", "Honda", "CR-V", "1995", "~"),
  r("SUV", "Hybrid", "Honda", "CR-V Hybrid", "2017", "~"),
  r("SUV", "Hydrogen", "Honda", "CR-V e:FCEV", "2024", "~"),
  r("SUV", "Petrol", "Honda", "WR-V", "2017", "~"),
  r("SUV", "Petrol", "Honda", "Pilot", "2002", "~"),
  r("SUV", "Petrol", "Honda", "Passport", "2018", "~"),
  r("SUV", "EV", "Honda", "e:Ny1", "2023", "~"),
  // Nissan
  r("SUV", "Petrol", "Nissan", "Kicks", "2016", "~"),
  r("SUV", "Hybrid", "Nissan", "Kicks e-Power", "2017", "~"),
  r("SUV", "Petrol", "Nissan", "Juke", "2010", "~"),
  r("SUV", "Petrol", "Nissan", "Qashqai", "2007", "~"),
  r("SUV", "Petrol", "Nissan", "X-Trail", "2000", "~"),
  r("SUV", "Hybrid", "Nissan", "X-Trail e-Power", "2022", "~"),
  r("SUV", "Petrol", "Nissan", "Murano", "2002", "~"),
  r("SUV", "Petrol", "Nissan", "Pathfinder", "1985", "~"),
  r("SUV", "EV", "Nissan", "Ariya", "2022", "~"),
  r("SUV", "EV", "Nissan", "Leaf", "2010", "~"),
  r("SUV", "Petrol", "Nissan", "Patrol", "1951", "~"),
  // Mazda
  r("SUV", "Petrol", "Mazda", "CX-3", "2015", "~"),
  r("SUV", "Petrol", "Mazda", "CX-30", "2019", "~"),
  r("SUV", "Petrol", "Mazda", "CX-5", "2012", "~"),
  r("SUV", "Diesel", "Mazda", "CX-5 Diesel", "2012", "~"),
  r("SUV", "Petrol", "Mazda", "CX-50", "2022", "~"),
  r("SUV", "Petrol", "Mazda", "CX-60", "2022", "~"),
  r("SUV", "PHEV", "Mazda", "CX-60 PHEV", "2022", "~"),
  r("SUV", "Petrol", "Mazda", "CX-8", "2017", "~"),
  r("SUV", "Petrol", "Mazda", "CX-9", "2007", "~"),
  r("SUV", "Petrol", "Mazda", "CX-90", "2023", "~"),
  r("SUV", "EV", "Mazda", "MX-30", "2020", "~"),
  // Hyundai / Kia
  r("SUV", "Petrol", "Hyundai", "Venue", "2019", "~"),
  r("SUV", "Petrol", "Hyundai", "Creta", "2014", "~"),
  r("SUV", "Petrol", "Hyundai", "Kona", "2017", "~"),
  r("SUV", "Hybrid", "Hyundai", "Kona Hybrid", "2019", "~"),
  r("SUV", "EV", "Hyundai", "Kona Electric", "2018", "~"),
  r("SUV", "Petrol", "Hyundai", "Tucson", "2004", "~"),
  r("SUV", "Hybrid", "Hyundai", "Tucson Hybrid", "2020", "~"),
  r("SUV", "Petrol", "Hyundai", "Santa Fe", "2000", "~"),
  r("SUV", "Hybrid", "Hyundai", "Santa Fe Hybrid", "2020", "~"),
  r("SUV", "Petrol", "Hyundai", "Palisade", "2018", "~"),
  r("SUV", "EV", "Hyundai", "Ioniq 5", "2021", "~"),
  r("SUV", "EV", "Hyundai", "Ioniq 5 N", "2024", "~"),
  r("SUV", "EV", "Hyundai", "Ioniq 6", "2022", "~"),
  r("SUV", "EV", "Hyundai", "Ioniq 9", "2025", "~"),
  r("SUV", "Petrol", "Kia", "Sonet", "2020", "~"),
  r("SUV", "Petrol", "Kia", "Seltos", "2019", "~"),
  r("SUV", "Petrol", "Kia", "Sportage", "1993", "~"),
  r("SUV", "Hybrid", "Kia", "Sportage Hybrid", "2022", "~"),
  r("SUV", "Petrol", "Kia", "Sorento", "2002", "~"),
  r("SUV", "Hybrid", "Kia", "Sorento Hybrid", "2020", "~"),
  r("SUV", "Petrol", "Kia", "Telluride", "2019", "~"),
  r("SUV", "EV", "Kia", "EV6", "2021", "~"),
  r("SUV", "EV", "Kia", "EV9", "2023", "~"),
  r("SUV", "EV", "Kia", "Niro EV", "2018", "~"),
  r("SUV", "Hybrid", "Kia", "Niro Hybrid", "2016", "~"),
  // Mitsubishi
  r("SUV", "Petrol", "Mitsubishi", "Outlander", "2001", "~"),
  r("SUV", "PHEV", "Mitsubishi", "Outlander PHEV", "2013", "~"),
  r("SUV", "Petrol", "Mitsubishi", "Eclipse Cross", "2017", "~"),
  r("SUV", "PHEV", "Mitsubishi", "Eclipse Cross PHEV", "2020", "~"),
  r("SUV", "Petrol", "Mitsubishi", "ASX", "2010", "~"),
  r("SUV", "Petrol", "Mitsubishi", "Pajero", "1982", "2021"),
  r("SUV", "Diesel", "Mitsubishi", "Pajero Sport", "1996", "~"),
  r("SUV", "Petrol", "Mitsubishi", "Xforce", "2023", "~"),
  // Subaru
  r("SUV", "Petrol", "Subaru", "Forester", "1997", "~"),
  r("SUV", "Hybrid", "Subaru", "Forester e-Boxer", "2018", "~"),
  r("SUV", "Petrol", "Subaru", "XV", "2011", "~"),
  r("SUV", "Petrol", "Subaru", "Crosstrek", "2012", "~"),
  r("SUV", "Petrol", "Subaru", "Outback", "1994", "~"),
  r("SUV", "Petrol", "Subaru", "Ascent", "2018", "~"),
  r("SUV", "EV", "Subaru", "Solterra", "2022", "~"),
  // BMW
  r("SUV", "Petrol", "BMW", "X1", "2009", "~"),
  r("SUV", "EV", "BMW", "iX1", "2022", "~"),
  r("SUV", "Petrol", "BMW", "X2", "2018", "~"),
  r("SUV", "EV", "BMW", "iX2", "2024", "~"),
  r("SUV", "Petrol", "BMW", "X3", "2003", "~"),
  r("SUV", "Diesel", "BMW", "X3 xDrive20d", "2003", "~"),
  r("SUV", "EV", "BMW", "iX3", "2020", "~"),
  r("SUV", "Petrol", "BMW", "X4", "2014", "~"),
  r("SUV", "Petrol", "BMW", "X5", "1999", "~"),
  r("SUV", "PHEV", "BMW", "X5 xDrive45e", "2019", "~"),
  r("SUV", "Diesel", "BMW", "X5 xDrive30d", "1999", "~"),
  r("SUV", "Petrol", "BMW", "X5 M", "2009", "~"),
  r("SUV", "Petrol", "BMW", "X6", "2008", "~"),
  r("SUV", "Petrol", "BMW", "X6 M", "2009", "~"),
  r("SUV", "Petrol", "BMW", "X7", "2018", "~"),
  r("SUV", "EV", "BMW", "iX", "2021", "~"),
  r("SUV", "Petrol", "BMW", "XM", "2022", "~"),
  // Mercedes
  r("SUV", "Petrol", "Mercedes-Benz", "GLA", "2014", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "GLB", "2019", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "GLC", "2015", "~"),
  r("SUV", "PHEV", "Mercedes-Benz", "GLC 300e", "2019", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "GLE", "2015", "~"),
  r("SUV", "Diesel", "Mercedes-Benz", "GLE 300d", "2015", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "GLE 53 AMG", "2019", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "GLE 63 AMG", "2019", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "GLS", "2015", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "GLS 600 Maybach", "2020", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "G-Class G500", "1979", "~"),
  r("SUV", "Petrol", "Mercedes-Benz", "G-Class G63 AMG", "1999", "~"),
  r("SUV", "EV", "Mercedes-Benz", "G580 EQ", "2024", "~"),
  r("SUV", "EV", "Mercedes-Benz", "EQA", "2021", "~"),
  r("SUV", "EV", "Mercedes-Benz", "EQB", "2021", "~"),
  r("SUV", "EV", "Mercedes-Benz", "EQC", "2019", "~"),
  r("SUV", "EV", "Mercedes-Benz", "EQE SUV", "2022", "~"),
  r("SUV", "EV", "Mercedes-Benz", "EQS SUV", "2022", "~"),
  // Audi
  r("SUV", "Petrol", "Audi", "Q2", "2016", "~"),
  r("SUV", "Petrol", "Audi", "Q3", "2011", "~"),
  r("SUV", "Petrol", "Audi", "Q5", "2008", "~"),
  r("SUV", "PHEV", "Audi", "Q5 TFSI e", "2019", "~"),
  r("SUV", "Petrol", "Audi", "Q7", "2005", "~"),
  r("SUV", "Petrol", "Audi", "Q8", "2018", "~"),
  r("SUV", "Petrol", "Audi", "RS Q8", "2020", "~"),
  r("SUV", "EV", "Audi", "Q4 e-tron", "2021", "~"),
  r("SUV", "EV", "Audi", "Q6 e-tron", "2024", "~"),
  r("SUV", "EV", "Audi", "Q8 e-tron", "2018", "~"),
  // Volvo / Porsche / Lexus
  r("SUV", "Petrol", "Volvo", "XC40", "2017", "~"),
  r("SUV", "EV", "Volvo", "XC40 Recharge", "2020", "~"),
  r("SUV", "EV", "Volvo", "EX30", "2024", "~"),
  r("SUV", "Petrol", "Volvo", "XC60", "2008", "~"),
  r("SUV", "PHEV", "Volvo", "XC60 T8", "2017", "~"),
  r("SUV", "Petrol", "Volvo", "XC90", "2002", "~"),
  r("SUV", "PHEV", "Volvo", "XC90 T8", "2015", "~"),
  r("SUV", "EV", "Volvo", "EX90", "2024", "~"),
  r("SUV", "EV", "Volvo", "C40 Recharge", "2021", "~"),
  r("SUV", "Petrol", "Porsche", "Macan", "2014", "~"),
  r("SUV", "EV", "Porsche", "Macan EV", "2024", "~"),
  r("SUV", "Petrol", "Porsche", "Cayenne", "2002", "~"),
  r("SUV", "Diesel", "Porsche", "Cayenne Diesel", "2009", "2018"),
  r("SUV", "PHEV", "Porsche", "Cayenne E-Hybrid", "2014", "~"),
  r("SUV", "Petrol", "Porsche", "Cayenne Turbo GT", "2021", "~"),
  r("SUV", "Petrol", "Lexus", "UX200", "2018", "~"),
  r("SUV", "Hybrid", "Lexus", "UX250h", "2018", "~"),
  r("SUV", "EV", "Lexus", "UX300e", "2020", "~"),
  r("SUV", "Petrol", "Lexus", "NX250", "2014", "~"),
  r("SUV", "Hybrid", "Lexus", "NX350h", "2014", "~"),
  r("SUV", "PHEV", "Lexus", "NX450h+", "2021", "~"),
  r("SUV", "Petrol", "Lexus", "RX350", "1998", "~"),
  r("SUV", "Hybrid", "Lexus", "RX450h", "2009", "~"),
  r("SUV", "PHEV", "Lexus", "RX500h", "2022", "~"),
  r("SUV", "Petrol", "Lexus", "GX460", "2009", "~"),
  r("SUV", "Petrol", "Lexus", "LX600", "1996", "~"),
  r("SUV", "EV", "Lexus", "RZ450e", "2023", "~"),
  // Ford / Chevrolet / Jeep / GMC
  r("SUV", "Petrol", "Ford", "EcoSport", "2003", "2022"),
  r("SUV", "Petrol", "Ford", "Escape", "2000", "~"),
  r("SUV", "Hybrid", "Ford", "Escape Hybrid", "2004", "~"),
  r("SUV", "Petrol", "Ford", "Edge", "2006", "2024"),
  r("SUV", "Petrol", "Ford", "Bronco", "2020", "~"),
  r("SUV", "Petrol", "Ford", "Bronco Sport", "2020", "~"),
  r("SUV", "Petrol", "Ford", "Everest", "2003", "~"),
  r("SUV", "Diesel", "Ford", "Everest Diesel", "2003", "~"),
  r("SUV", "Petrol", "Ford", "Explorer", "1990", "~"),
  r("SUV", "Petrol", "Ford", "Expedition", "1996", "~"),
  r("SUV", "EV", "Ford", "Mustang Mach-E", "2021", "~"),
  r("SUV", "EV", "Ford", "Explorer EV", "2024", "~"),
  r("SUV", "Petrol", "Chevrolet", "Trax", "2012", "~"),
  r("SUV", "Petrol", "Chevrolet", "Trailblazer", "2001", "~"),
  r("SUV", "Petrol", "Chevrolet", "Equinox", "2004", "~"),
  r("SUV", "EV", "Chevrolet", "Equinox EV", "2024", "~"),
  r("SUV", "Petrol", "Chevrolet", "Tahoe", "1995", "~"),
  r("SUV", "Petrol", "Chevrolet", "Suburban", "1935", "~"),
  r("SUV", "EV", "Chevrolet", "Blazer EV", "2023", "~"),
  r("SUV", "Petrol", "GMC", "Yukon", "1991", "~"),
  r("SUV", "EV", "GMC", "Hummer EV SUV", "2023", "~"),
  r("SUV", "Petrol", "Jeep", "Renegade", "2014", "~"),
  r("SUV", "Petrol", "Jeep", "Compass", "2006", "~"),
  r("SUV", "Petrol", "Jeep", "Cherokee", "1974", "~"),
  r("SUV", "Petrol", "Jeep", "Wrangler", "1986", "~"),
  r("SUV", "PHEV", "Jeep", "Wrangler 4xe", "2021", "~"),
  r("SUV", "Petrol", "Jeep", "Grand Cherokee", "1992", "~"),
  r("SUV", "PHEV", "Jeep", "Grand Cherokee 4xe", "2021", "~"),
  r("SUV", "Petrol", "Jeep", "Wagoneer", "1962", "~"),
  r("SUV", "EV", "Jeep", "Avenger", "2023", "~"),
  r("SUV", "Petrol", "Land Rover", "Range Rover", "1970", "~"),
  r("SUV", "Diesel", "Land Rover", "Range Rover Diesel", "1970", "~"),
  r("SUV", "Petrol", "Land Rover", "Range Rover Sport", "2005", "~"),
  r("SUV", "Petrol", "Land Rover", "Range Rover Velar", "2017", "~"),
  r("SUV", "Petrol", "Land Rover", "Range Rover Evoque", "2011", "~"),
  r("SUV", "Petrol", "Land Rover", "Defender", "1983", "~"),
  r("SUV", "Petrol", "Land Rover", "Discovery", "1989", "~"),
  r("SUV", "Petrol", "Land Rover", "Discovery Sport", "2014", "~"),
  // Tesla / BYD / Xpeng / NIO / Rivian / Smart / Zeekr / MG / Lynk & Co
  r("SUV", "EV", "Tesla", "Model Y", "2020", "~"),
  r("SUV", "EV", "Tesla", "Model X", "2015", "~"),
  r("SUV", "EV", "Tesla", "Model X Plaid", "2021", "~"),
  r("SUV", "EV", "BYD", "Atto 3", "2022", "~"),
  r("SUV", "EV", "BYD", "Yuan Plus", "2022", "~"),
  r("SUV", "EV", "BYD", "Tang", "2018", "~"),
  r("SUV", "PHEV", "BYD", "Tang DM-i", "2021", "~"),
  r("SUV", "EV", "BYD", "Song Plus", "2020", "~"),
  r("SUV", "PHEV", "BYD", "Sealion 6", "2023", "~"),
  r("SUV", "EV", "BYD", "Sealion 7", "2024", "~"),
  r("SUV", "EV", "Xpeng", "G3", "2018", "~"),
  r("SUV", "EV", "Xpeng", "G6", "2023", "~"),
  r("SUV", "EV", "Xpeng", "G9", "2022", "~"),
  r("SUV", "EV", "NIO", "ES6", "2018", "~"),
  r("SUV", "EV", "NIO", "ES7", "2022", "~"),
  r("SUV", "EV", "NIO", "ES8", "2018", "~"),
  r("SUV", "EV", "NIO", "EC6", "2020", "~"),
  r("SUV", "EV", "Rivian", "R1S", "2022", "~"),
  r("SUV", "EV", "Smart", "#1", "2022", "~"),
  r("SUV", "EV", "Smart", "#3", "2023", "~"),
  r("SUV", "EV", "Zeekr", "X", "2023", "~"),
  r("SUV", "EV", "MG", "ZS EV", "2019", "~"),
  r("SUV", "Petrol", "MG", "HS", "2018", "~"),
  r("SUV", "PHEV", "MG", "HS PHEV", "2020", "~"),
  r("SUV", "EV", "MG", "Marvel R", "2021", "~"),
  r("SUV", "EV", "Volkswagen", "ID.4", "2020", "~"),
  r("SUV", "EV", "Volkswagen", "ID.5", "2021", "~"),
  r("SUV", "EV", "Volkswagen", "ID.6", "2021", "~"),
  r("SUV", "EV", "Volkswagen", "ID.7 Tourer", "2024", "~"),
  r("SUV", "Petrol", "Volkswagen", "Tiguan", "2007", "~"),
  r("SUV", "Petrol", "Volkswagen", "Touareg", "2002", "~"),
  r("SUV", "Petrol", "Volkswagen", "T-Roc", "2017", "~"),
  r("SUV", "Petrol", "Volkswagen", "T-Cross", "2018", "~"),
  r("SUV", "Petrol", "Volkswagen", "Atlas", "2017", "~"),
  // Lynk & Co / GWM / Chery / Geely
  r("SUV", "Petrol", "Lynk & Co", "01", "2017", "~"),
  r("SUV", "Petrol", "Lynk & Co", "02", "2018", "~"),
  r("SUV", "Petrol", "Lynk & Co", "06", "2020", "~"),
  r("SUV", "EV", "Lynk & Co", "Z10", "2024", "~"),
  r("SUV", "Petrol", "GWM", "Haval H6", "2011", "~"),
  r("SUV", "Petrol", "GWM", "Haval Jolion", "2020", "~"),
  r("SUV", "Petrol", "GWM", "Tank 300", "2021", "~"),
  r("SUV", "Petrol", "GWM", "Tank 500", "2021", "~"),
  r("SUV", "Petrol", "Chery", "Tiggo 7 Pro", "2020", "~"),
  r("SUV", "Petrol", "Chery", "Tiggo 8 Pro", "2018", "~"),
  r("SUV", "Petrol", "Chery", "Omoda 5", "2022", "~"),
  r("SUV", "EV", "Chery", "Omoda E5", "2023", "~"),
  r("SUV", "Petrol", "Chery", "Jaecoo J7", "2023", "~"),
  r("SUV", "Petrol", "Geely", "Coolray", "2018", "~"),
  r("SUV", "Petrol", "Geely", "Atlas", "2016", "~"),
  r("SUV", "Petrol", "Geely", "Boyue", "2016", "~"),
  // Ferrari / Lamborghini / Aston Martin / Bentley / Rolls-Royce / Maserati
  r("SUV", "Petrol", "Ferrari", "Purosangue", "2022", "~"),
  r("SUV", "Petrol", "Lamborghini", "Urus", "2018", "~"),
  r("SUV", "PHEV", "Lamborghini", "Urus SE", "2024", "~"),
  r("SUV", "Petrol", "Aston Martin", "DBX", "2020", "~"),
  r("SUV", "Petrol", "Bentley", "Bentayga", "2015", "~"),
  r("SUV", "PHEV", "Bentley", "Bentayga Hybrid", "2018", "~"),
  r("SUV", "Petrol", "Rolls-Royce", "Cullinan", "2018", "~"),
  r("SUV", "Petrol", "Maserati", "Levante", "2016", "~"),
  r("SUV", "Petrol", "Maserati", "Grecale", "2022", "~"),
  r("SUV", "EV", "Maserati", "Grecale Folgore", "2024", "~"),
  r("SUV", "Petrol", "Jaguar", "F-Pace", "2016", "~"),
  r("SUV", "Petrol", "Jaguar", "E-Pace", "2017", "~"),
  r("SUV", "EV", "Jaguar", "I-Pace", "2018", "~"),
  // Cadillac / Lincoln / Buick / Acura / Infiniti
  r("SUV", "Petrol", "Cadillac", "XT4", "2018", "~"),
  r("SUV", "Petrol", "Cadillac", "XT5", "2016", "~"),
  r("SUV", "Petrol", "Cadillac", "Escalade", "1998", "~"),
  r("SUV", "EV", "Cadillac", "Lyriq", "2022", "~"),
  r("SUV", "EV", "Cadillac", "Escalade IQ", "2024", "~"),
  r("SUV", "Petrol", "Lincoln", "Navigator", "1997", "~"),
  r("SUV", "Petrol", "Lincoln", "Aviator", "2002", "~"),
  r("SUV", "Petrol", "Lincoln", "Nautilus", "2018", "~"),
  r("SUV", "Petrol", "Acura", "MDX", "2000", "~"),
  r("SUV", "Petrol", "Acura", "RDX", "2006", "~"),
  r("SUV", "Petrol", "Infiniti", "QX50", "2013", "~"),
  r("SUV", "Petrol", "Infiniti", "QX60", "2012", "~"),
  r("SUV", "Petrol", "Infiniti", "QX80", "2010", "~"),
  // Genesis
  r("SUV", "Petrol", "Genesis", "GV70", "2020", "~"),
  r("SUV", "EV", "Genesis", "GV70 Electrified", "2022", "~"),
  r("SUV", "Petrol", "Genesis", "GV80", "2020", "~"),
  r("SUV", "EV", "Genesis", "GV60", "2021", "~"),
  // Polestar / Lucid / Lotus
  r("SUV", "EV", "Polestar", "3", "2023", "~"),
  r("SUV", "EV", "Polestar", "4", "2024", "~"),
  r("SUV", "EV", "Lucid", "Gravity", "2024", "~"),
  r("SUV", "EV", "Lotus", "Eletre", "2023", "~"),
  // Fisker / VinFast
  r("SUV", "EV", "Fisker", "Ocean", "2022", "2024"),
  r("SUV", "EV", "VinFast", "VF8", "2022", "~"),
  r("SUV", "EV", "VinFast", "VF9", "2023", "~"),
];

// ---------------- MPV / MINIVAN ----------------
const MPV: R[] = [
  r("MPV", "Petrol", "Proton", "Exora", "2009", "~"),
  r("MPV", "Petrol", "Perodua", "Alza", "2009", "~"),
  r("MPV", "Petrol", "Toyota", "Avanza", "2003", "~"),
  r("MPV", "Petrol", "Toyota", "Veloz", "2021", "~"),
  r("MPV", "Petrol", "Toyota", "Innova", "2004", "~"),
  r("MPV", "Diesel", "Toyota", "Innova Diesel", "2004", "~"),
  r("MPV", "Hybrid", "Toyota", "Innova Zenix Hybrid", "2022", "~"),
  r("MPV", "Petrol", "Toyota", "Sienta", "2003", "~"),
  r("MPV", "Hybrid", "Toyota", "Sienta Hybrid", "2015", "~"),
  r("MPV", "Petrol", "Toyota", "Sienna", "1997", "~"),
  r("MPV", "Hybrid", "Toyota", "Sienna Hybrid", "2020", "~"),
  r("MPV", "Petrol", "Toyota", "Voxy", "2001", "~"),
  r("MPV", "Hybrid", "Toyota", "Voxy Hybrid", "2014", "~"),
  r("MPV", "Petrol", "Toyota", "Noah", "2001", "~"),
  r("MPV", "Petrol", "Toyota", "Estima", "1990", "2019"),
  r("MPV", "Petrol", "Toyota", "Alphard", "2002", "~"),
  r("MPV", "Hybrid", "Toyota", "Alphard Hybrid", "2011", "~"),
  r("MPV", "Petrol", "Toyota", "Vellfire", "2008", "~"),
  r("MPV", "Hybrid", "Toyota", "Vellfire Hybrid", "2011", "~"),
  r("MPV", "Petrol", "Honda", "Odyssey", "1994", "~"),
  r("MPV", "Hybrid", "Honda", "Odyssey Hybrid", "2016", "~"),
  r("MPV", "Petrol", "Honda", "BR-V", "2015", "~"),
  r("MPV", "Petrol", "Honda", "Freed", "2008", "~"),
  r("MPV", "Hybrid", "Honda", "Freed Hybrid", "2011", "~"),
  r("MPV", "Petrol", "Honda", "Stepwgn", "1996", "~"),
  r("MPV", "Petrol", "Nissan", "Serena", "1991", "~"),
  r("MPV", "Hybrid", "Nissan", "Serena e-Power", "2018", "~"),
  r("MPV", "Petrol", "Nissan", "Grand Livina", "2006", "~"),
  r("MPV", "Petrol", "Nissan", "Elgrand", "1997", "~"),
  r("MPV", "Petrol", "Nissan", "Quest", "1992", "2017"),
  r("MPV", "Petrol", "Mitsubishi", "Xpander", "2017", "~"),
  r("MPV", "Petrol", "Mitsubishi", "Delica", "1968", "~"),
  r("MPV", "Petrol", "Hyundai", "Starex", "1997", "~"),
  r("MPV", "Diesel", "Hyundai", "Starex Diesel", "1997", "~"),
  r("MPV", "Petrol", "Hyundai", "Staria", "2021", "~"),
  r("MPV", "Petrol", "Kia", "Carnival", "1998", "~"),
  r("MPV", "Diesel", "Kia", "Carnival Diesel", "1998", "~"),
  r("MPV", "Hybrid", "Kia", "Carnival Hybrid", "2024", "~"),
  r("MPV", "Petrol", "Mercedes-Benz", "V-Class", "2014", "~"),
  r("MPV", "EV", "Mercedes-Benz", "EQV", "2020", "~"),
  r("MPV", "Petrol", "Volkswagen", "Caddy", "1979", "~"),
  r("MPV", "Petrol", "Volkswagen", "Touran", "2003", "~"),
  r("MPV", "Petrol", "Volkswagen", "Sharan", "1995", "2022"),
  r("MPV", "EV", "Volkswagen", "ID. Buzz", "2022", "~"),
  r("MPV", "Petrol", "Lexus", "LM350", "2019", "~"),
  r("MPV", "Hybrid", "Lexus", "LM500h", "2023", "~"),
  r("MPV", "Petrol", "Chrysler", "Pacifica", "2016", "~"),
  r("MPV", "PHEV", "Chrysler", "Pacifica Hybrid", "2017", "~"),
  r("MPV", "Petrol", "Chrysler", "Voyager", "1983", "~"),
  r("MPV", "Petrol", "Dodge", "Grand Caravan", "1983", "2020"),
  r("MPV", "Petrol", "Renault", "Espace", "1984", "~"),
  r("MPV", "EV", "Zeekr", "009", "2022", "~"),
  r("MPV", "EV", "BYD", "Denza D9", "2022", "~"),
  r("MPV", "EV", "Xpeng", "X9", "2024", "~"),
];

// ---------------- PICK UP ----------------
const PICKUP: R[] = [
  r("Pick Up", "Diesel", "Toyota", "Hilux", "1968", "~"),
  r("Pick Up", "Petrol", "Toyota", "Hilux Petrol", "1968", "~"),
  r("Pick Up", "Petrol", "Toyota", "Tacoma", "1995", "~"),
  r("Pick Up", "Hybrid", "Toyota", "Tacoma Hybrid", "2024", "~"),
  r("Pick Up", "Petrol", "Toyota", "Tundra", "1999", "~"),
  r("Pick Up", "Hybrid", "Toyota", "Tundra Hybrid", "2022", "~"),
  r("Pick Up", "Diesel", "Ford", "Ranger", "1983", "~"),
  r("Pick Up", "Petrol", "Ford", "Ranger Petrol", "1983", "~"),
  r("Pick Up", "Diesel", "Ford", "Ranger Raptor", "2018", "~"),
  r("Pick Up", "Petrol", "Ford", "Ranger Raptor Petrol", "2022", "~"),
  r("Pick Up", "Petrol", "Ford", "F-150", "1975", "~"),
  r("Pick Up", "Petrol", "Ford", "F-150 Raptor", "2010", "~"),
  r("Pick Up", "EV", "Ford", "F-150 Lightning", "2022", "~"),
  r("Pick Up", "Petrol", "Ford", "F-250 Super Duty", "1999", "~"),
  r("Pick Up", "Diesel", "Ford", "F-350 Super Duty", "1999", "~"),
  r("Pick Up", "Petrol", "Ford", "Maverick", "2021", "~"),
  r("Pick Up", "Hybrid", "Ford", "Maverick Hybrid", "2021", "~"),
  r("Pick Up", "Diesel", "Mitsubishi", "Triton", "1978", "~"),
  r("Pick Up", "Diesel", "Mazda", "BT-50", "2006", "~"),
  r("Pick Up", "Diesel", "Isuzu", "D-Max", "2002", "~"),
  r("Pick Up", "Diesel", "Isuzu", "D-Max V-Cross", "2018", "~"),
  r("Pick Up", "Diesel", "Nissan", "Navara", "1985", "~"),
  r("Pick Up", "Petrol", "Nissan", "Frontier", "1997", "~"),
  r("Pick Up", "Petrol", "Nissan", "Titan", "2003", "2024"),
  r("Pick Up", "Diesel", "Volkswagen", "Amarok", "2010", "~"),
  r("Pick Up", "Petrol", "Chevrolet", "Silverado", "1998", "~"),
  r("Pick Up", "Diesel", "Chevrolet", "Silverado Duramax", "2001", "~"),
  r("Pick Up", "EV", "Chevrolet", "Silverado EV", "2024", "~"),
  r("Pick Up", "Petrol", "Chevrolet", "Colorado", "2003", "~"),
  r("Pick Up", "Petrol", "GMC", "Sierra", "1987", "~"),
  r("Pick Up", "EV", "GMC", "Sierra EV", "2024", "~"),
  r("Pick Up", "EV", "GMC", "Hummer EV", "2021", "~"),
  r("Pick Up", "Petrol", "GMC", "Canyon", "2003", "~"),
  r("Pick Up", "Diesel", "RAM", "1500", "1981", "~"),
  r("Pick Up", "Petrol", "RAM", "1500 TRX", "2020", "2024"),
  r("Pick Up", "EV", "RAM", "1500 REV", "2024", "~"),
  r("Pick Up", "Diesel", "RAM", "2500", "1981", "~"),
  r("Pick Up", "Diesel", "RAM", "3500", "1981", "~"),
  r("Pick Up", "Petrol", "Jeep", "Gladiator", "2019", "~"),
  r("Pick Up", "Petrol", "Honda", "Ridgeline", "2005", "~"),
  r("Pick Up", "EV", "Tesla", "Cybertruck", "2023", "~"),
  r("Pick Up", "EV", "Rivian", "R1T", "2021", "~"),
  r("Pick Up", "Petrol", "GWM", "Cannon", "2019", "~"),
  r("Pick Up", "Diesel", "GWM", "Cannon Diesel", "2019", "~"),
  r("Pick Up", "Petrol", "GWM", "Tank 300 Pickup", "2023", "~"),
  r("Pick Up", "Diesel", "SsangYong", "Musso", "1993", "~"),
  r("Pick Up", "Petrol", "Maxus", "T60", "2017", "~"),
  r("Pick Up", "EV", "Maxus", "T90 EV", "2022", "~"),
  r("Pick Up", "EV", "BYD", "Shark", "2024", "~"),
];

// ---------------- VAN ----------------
const VAN: R[] = [
  r("Van", "Diesel", "Toyota", "Hiace", "1967", "~"),
  r("Van", "Petrol", "Toyota", "Hiace Petrol", "1967", "~"),
  r("Van", "Diesel", "Toyota", "Granvia", "2019", "~"),
  r("Van", "Diesel", "Mercedes-Benz", "Sprinter", "1995", "~"),
  r("Van", "EV", "Mercedes-Benz", "eSprinter", "2019", "~"),
  r("Van", "Diesel", "Mercedes-Benz", "Vito", "1996", "~"),
  r("Van", "EV", "Mercedes-Benz", "eVito", "2018", "~"),
  r("Van", "Diesel", "Volkswagen", "Transporter", "1950", "~"),
  r("Van", "Diesel", "Volkswagen", "Crafter", "2006", "~"),
  r("Van", "EV", "Volkswagen", "ID. Buzz Cargo", "2022", "~"),
  r("Van", "Diesel", "Ford", "Transit", "1965", "~"),
  r("Van", "Diesel", "Ford", "Transit Custom", "2012", "~"),
  r("Van", "EV", "Ford", "E-Transit", "2022", "~"),
  r("Van", "EV", "Ford", "E-Transit Custom", "2024", "~"),
  r("Van", "Diesel", "Hyundai", "H-1", "1997", "~"),
  r("Van", "Diesel", "Hyundai", "H350", "2015", "~"),
  r("Van", "Diesel", "Hyundai", "Porter", "1977", "~"),
  r("Van", "Diesel", "Renault", "Trafic", "1980", "~"),
  r("Van", "Diesel", "Renault", "Master", "1980", "~"),
  r("Van", "EV", "Renault", "Master E-Tech", "2022", "~"),
  r("Van", "Diesel", "Peugeot", "Expert", "1995", "~"),
  r("Van", "Diesel", "Peugeot", "Boxer", "1994", "~"),
  r("Van", "EV", "Peugeot", "e-Expert", "2020", "~"),
  r("Van", "Diesel", "Citroen", "Jumper", "1994", "~"),
  r("Van", "Diesel", "Citroen", "Berlingo", "1996", "~"),
  r("Van", "EV", "Citroen", "e-Berlingo", "2021", "~"),
  r("Van", "Diesel", "Fiat", "Ducato", "1981", "~"),
  r("Van", "EV", "Fiat", "E-Ducato", "2020", "~"),
  r("Van", "Diesel", "Iveco", "Daily", "1978", "~"),
  r("Van", "EV", "Iveco", "eDaily", "2022", "~"),
  r("Van", "Diesel", "Nissan", "NV200", "2009", "~"),
  r("Van", "Diesel", "Nissan", "NV350 Caravan", "2012", "~"),
  r("Van", "EV", "Nissan", "Townstar EV", "2022", "~"),
  r("Van", "Petrol", "Suzuki", "APV", "2004", "~"),
  r("Van", "Petrol", "Suzuki", "Carry", "1961", "~"),
  r("Van", "EV", "Maxus", "MIFA 9", "2021", "~"),
  r("Van", "Diesel", "Maxus", "Deliver 9", "2019", "~"),
  r("Van", "EV", "Maxus", "eDeliver 9", "2020", "~"),
  r("Van", "Diesel", "LDV", "V80", "2012", "~"),
  r("Van", "EV", "LDV", "EV80", "2018", "~"),
];

// ---------------- TRUCK / LORRY ----------------
const TRUCK: R[] = [
  r("Truck", "Diesel", "Hino", "Series 300", "2002", "~"),
  r("Truck", "Diesel", "Hino", "Series 500", "2002", "~"),
  r("Truck", "Diesel", "Hino", "Series 700", "2002", "~"),
  r("Truck", "Diesel", "Hino", "Dutro", "1999", "~"),
  r("Truck", "Diesel", "Hino", "Ranger", "1980", "~"),
  r("Truck", "Diesel", "Isuzu", "ELF", "1959", "~"),
  r("Truck", "Diesel", "Isuzu", "Forward", "1970", "~"),
  r("Truck", "Diesel", "Isuzu", "Giga", "1994", "~"),
  r("Truck", "Diesel", "Isuzu", "F-Series", "1970", "~"),
  r("Truck", "Diesel", "Mitsubishi Fuso", "Canter", "1963", "~"),
  r("Truck", "Diesel", "Mitsubishi Fuso", "Fighter", "1984", "~"),
  r("Truck", "Diesel", "Mitsubishi Fuso", "Super Great", "1996", "~"),
  r("Truck", "EV", "Mitsubishi Fuso", "eCanter", "2017", "~"),
  r("Truck", "Diesel", "UD Trucks", "Quester", "2013", "~"),
  r("Truck", "Diesel", "UD Trucks", "Quon", "2004", "~"),
  r("Truck", "Diesel", "UD Trucks", "Croner", "2017", "~"),
  r("Truck", "Diesel", "UD Trucks", "Kuzer", "2017", "~"),
  r("Truck", "Diesel", "Scania", "P-Series", "2004", "~"),
  r("Truck", "Diesel", "Scania", "G-Series", "2007", "~"),
  r("Truck", "Diesel", "Scania", "R-Series", "2004", "~"),
  r("Truck", "Diesel", "Scania", "S-Series", "2017", "~"),
  r("Truck", "EV", "Scania", "BEV Truck", "2020", "~"),
  r("Truck", "Diesel", "Volvo", "FL", "1985", "~"),
  r("Truck", "Diesel", "Volvo", "FE", "2006", "~"),
  r("Truck", "Diesel", "Volvo", "FH", "1993", "~"),
  r("Truck", "Diesel", "Volvo", "FH16", "1993", "~"),
  r("Truck", "Diesel", "Volvo", "FM", "1998", "~"),
  r("Truck", "Diesel", "Volvo", "FMX", "2010", "~"),
  r("Truck", "EV", "Volvo", "FH Electric", "2022", "~"),
  r("Truck", "EV", "Volvo", "FE Electric", "2019", "~"),
  r("Truck", "EV", "Volvo", "FL Electric", "2019", "~"),
  r("Truck", "Diesel", "Mercedes-Benz", "Atego", "1998", "~"),
  r("Truck", "Diesel", "Mercedes-Benz", "Axor", "2001", "2014"),
  r("Truck", "Diesel", "Mercedes-Benz", "Actros", "1996", "~"),
  r("Truck", "Diesel", "Mercedes-Benz", "Arocs", "2013", "~"),
  r("Truck", "EV", "Mercedes-Benz", "eActros", "2021", "~"),
  r("Truck", "EV", "Mercedes-Benz", "eActros 600", "2024", "~"),
  r("Truck", "Diesel", "MAN", "TGL", "2005", "~"),
  r("Truck", "Diesel", "MAN", "TGM", "2005", "~"),
  r("Truck", "Diesel", "MAN", "TGS", "2007", "~"),
  r("Truck", "Diesel", "MAN", "TGX", "2007", "~"),
  r("Truck", "EV", "MAN", "eTGX", "2024", "~"),
  r("Truck", "Diesel", "DAF", "LF", "2001", "~"),
  r("Truck", "Diesel", "DAF", "CF", "2000", "~"),
  r("Truck", "Diesel", "DAF", "XF", "1997", "~"),
  r("Truck", "Diesel", "DAF", "XG", "2021", "~"),
  r("Truck", "EV", "DAF", "XD Electric", "2023", "~"),
  r("Truck", "Diesel", "Iveco", "Eurocargo", "1991", "~"),
  r("Truck", "Diesel", "Iveco", "Stralis", "2002", "2019"),
  r("Truck", "Diesel", "Iveco", "S-Way", "2019", "~"),
  r("Truck", "EV", "Iveco", "S-eWay", "2024", "~"),
  r("Truck", "EV", "Tesla", "Semi", "2022", "~"),
  r("Truck", "Diesel", "Kenworth", "T680", "2011", "~"),
  r("Truck", "EV", "Kenworth", "T680E", "2021", "~"),
  r("Truck", "Diesel", "Peterbilt", "579", "2012", "~"),
  r("Truck", "EV", "Peterbilt", "579EV", "2021", "~"),
  r("Truck", "Diesel", "Freightliner", "Cascadia", "2007", "~"),
  r("Truck", "EV", "Freightliner", "eCascadia", "2022", "~"),
  r("Truck", "Diesel", "International", "LT Series", "2017", "~"),
  r("Truck", "Diesel", "Mack", "Anthem", "2017", "~"),
  r("Truck", "EV", "Nikola", "Tre BEV", "2022", "~"),
  r("Truck", "Hydrogen", "Nikola", "Tre FCEV", "2023", "~"),
  r("Truck", "EV", "BYD", "Q1M", "2020", "~"),
  r("Truck", "Diesel", "Sinotruk", "HOWO", "2004", "~"),
  r("Truck", "Diesel", "FAW", "Jiefang J7", "2018", "~"),
  r("Truck", "Diesel", "Foton", "Auman", "2002", "~"),
  r("Truck", "Diesel", "JAC", "N-Series", "2010", "~"),
  r("Truck", "Diesel", "Tata", "Prima", "2009", "~"),
  r("Truck", "Diesel", "Ashok Leyland", "Boss", "2014", "~"),
];

// ---------------- BUS ----------------
const BUS: R[] = [
  r("Bus", "Diesel", "Mercedes-Benz", "Citaro", "1997", "~"),
  r("Bus", "EV", "Mercedes-Benz", "eCitaro", "2018", "~"),
  r("Bus", "Diesel", "Mercedes-Benz", "Tourismo", "1994", "~"),
  r("Bus", "Diesel", "Mercedes-Benz", "Travego", "1999", "~"),
  r("Bus", "Diesel", "Setra", "MultiClass", "2002", "~"),
  r("Bus", "Diesel", "Setra", "ComfortClass", "2012", "~"),
  r("Bus", "Diesel", "Setra", "TopClass", "2012", "~"),
  r("Bus", "Diesel", "Volvo", "B8R", "2014", "~"),
  r("Bus", "Diesel", "Volvo", "B11R", "2011", "~"),
  r("Bus", "Diesel", "Volvo", "9700", "2001", "~"),
  r("Bus", "EV", "Volvo", "7900 Electric", "2018", "~"),
  r("Bus", "EV", "Volvo", "BZL Electric", "2022", "~"),
  r("Bus", "Diesel", "Scania", "K-Series", "2005", "~"),
  r("Bus", "Diesel", "Scania", "F-Series", "2010", "~"),
  r("Bus", "Diesel", "Scania", "Touring", "2010", "~"),
  r("Bus", "Diesel", "Hino", "RM1", "2006", "~"),
  r("Bus", "Diesel", "Hino", "RK8", "2010", "~"),
  r("Bus", "Diesel", "Hino", "Selega", "2000", "~"),
  r("Bus", "Diesel", "Higer", "KLQ6128", "2008", "~"),
  r("Bus", "Diesel", "Higer", "KLQ6122", "2008", "~"),
  r("Bus", "Diesel", "King Long", "XMQ6127", "2010", "~"),
  r("Bus", "Diesel", "King Long", "XMQ6900", "2010", "~"),
  r("Bus", "EV", "BYD", "K9", "2010", "~"),
  r("Bus", "EV", "BYD", "B12", "2017", "~"),
  r("Bus", "EV", "BYD", "K7", "2014", "~"),
  r("Bus", "EV", "BYD", "ADL Enviro200EV", "2015", "~"),
  r("Bus", "EV", "Yutong", "E12", "2019", "~"),
  r("Bus", "EV", "Yutong", "E10", "2018", "~"),
  r("Bus", "EV", "Yutong", "T12E", "2020", "~"),
  r("Bus", "Diesel", "Iveco", "Crossway", "2006", "~"),
  r("Bus", "Diesel", "Iveco", "Magelys", "2004", "2019"),
  r("Bus", "CNG", "MAN", "Lion's City", "1998", "~"),
  r("Bus", "EV", "MAN", "Lion's City E", "2020", "~"),
  r("Bus", "Diesel", "MAN", "Lion's Coach", "1996", "~"),
  r("Bus", "Diesel", "Neoplan", "Cityliner", "1971", "~"),
  r("Bus", "Diesel", "Neoplan", "Tourliner", "2006", "~"),
  r("Bus", "Diesel", "Solaris", "Urbino 12", "1999", "~"),
  r("Bus", "EV", "Solaris", "Urbino Electric", "2013", "~"),
  r("Bus", "Hydrogen", "Solaris", "Urbino Hydrogen", "2019", "~"),
  r("Bus", "EV", "Proterra", "ZX5", "2020", "~"),
  r("Bus", "EV", "New Flyer", "Xcelsior CHARGE", "2017", "~"),
  r("Bus", "Diesel", "Tata", "Starbus", "2007", "~"),
  r("Bus", "EV", "Tata", "Starbus EV", "2017", "~"),
  r("Bus", "Diesel", "Ashok Leyland", "Viking", "1979", "~"),
  r("Bus", "EV", "Ashok Leyland", "Switch EiV 22", "2022", "~"),
];

// ---------------- MOTORCYCLE / BIKE ----------------
const BIKE: R[] = [
  // Yamaha
  r("Bike", "Petrol", "Yamaha", "Y15ZR", "2015", "~"),
  r("Bike", "Petrol", "Yamaha", "Y16ZR", "2021", "~"),
  r("Bike", "Petrol", "Yamaha", "LC135", "2007", "~"),
  r("Bike", "Petrol", "Yamaha", "Lagenda 115Z", "2014", "~"),
  r("Bike", "Petrol", "Yamaha", "MT-03", "2016", "~"),
  r("Bike", "Petrol", "Yamaha", "MT-07", "2014", "~"),
  r("Bike", "Petrol", "Yamaha", "MT-09", "2014", "~"),
  r("Bike", "Petrol", "Yamaha", "MT-10", "2016", "~"),
  r("Bike", "Petrol", "Yamaha", "MT-15", "2018", "~"),
  r("Bike", "Petrol", "Yamaha", "MT-25", "2015", "~"),
  r("Bike", "Petrol", "Yamaha", "R3", "2014", "~"),
  r("Bike", "Petrol", "Yamaha", "R7", "2021", "~"),
  r("Bike", "Petrol", "Yamaha", "R15", "2008", "~"),
  r("Bike", "Petrol", "Yamaha", "R25", "2014", "~"),
  r("Bike", "Petrol", "Yamaha", "R6", "1999", "2020"),
  r("Bike", "Petrol", "Yamaha", "R1", "1998", "~"),
  r("Bike", "Petrol", "Yamaha", "R1M", "2015", "~"),
  r("Bike", "Petrol", "Yamaha", "FZ150i", "2009", "~"),
  r("Bike", "Petrol", "Yamaha", "Tenere 700", "2019", "~"),
  r("Bike", "Petrol", "Yamaha", "Niken GT", "2018", "~"),
  r("Bike", "Petrol", "Yamaha", "VMAX", "1985", "2020"),
  // Honda Bikes
  r("Bike", "Petrol", "Honda", "Wave 110", "1995", "~"),
  r("Bike", "Petrol", "Honda", "Wave 125", "2002", "~"),
  r("Bike", "Petrol", "Honda", "Dash 110", "2009", "~"),
  r("Bike", "Petrol", "Honda", "RS150R", "2016", "~"),
  r("Bike", "Petrol", "Honda", "RS-X", "2022", "~"),
  r("Bike", "Petrol", "Honda", "Winner X", "2020", "~"),
  r("Bike", "Petrol", "Honda", "CB150R Streetfire", "2015", "~"),
  r("Bike", "Petrol", "Honda", "CBR150R", "2002", "~"),
  r("Bike", "Petrol", "Honda", "CBR250RR", "2016", "~"),
  r("Bike", "Petrol", "Honda", "CBR500R", "2013", "~"),
  r("Bike", "Petrol", "Honda", "CBR650R", "2019", "~"),
  r("Bike", "Petrol", "Honda", "CBR1000RR", "2004", "~"),
  r("Bike", "Petrol", "Honda", "CBR1000RR-R Fireblade", "2020", "~"),
  r("Bike", "Petrol", "Honda", "CB300R", "2018", "~"),
  r("Bike", "Petrol", "Honda", "CB500F", "2013", "~"),
  r("Bike", "Petrol", "Honda", "CB650R", "2019", "~"),
  r("Bike", "Petrol", "Honda", "CB1000R", "2008", "~"),
  r("Bike", "Petrol", "Honda", "Africa Twin", "1988", "~"),
  r("Bike", "Petrol", "Honda", "Africa Twin Adventure Sports", "2018", "~"),
  r("Bike", "Petrol", "Honda", "NC750X", "2014", "~"),
  r("Bike", "Petrol", "Honda", "Goldwing", "1975", "~"),
  // Kawasaki
  r("Bike", "Petrol", "Kawasaki", "Ninja 250", "2008", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja 300", "2012", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja 400", "2018", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja 500", "2024", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja 650", "2009", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja ZX-4RR", "2023", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja ZX-6R", "1995", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja ZX-10R", "2004", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja ZX-10RR", "2017", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja H2", "2015", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja H2R", "2015", "~"),
  r("Bike", "Petrol", "Kawasaki", "Z400", "2018", "~"),
  r("Bike", "Petrol", "Kawasaki", "Z650", "2017", "~"),
  r("Bike", "Petrol", "Kawasaki", "Z900", "2017", "~"),
  r("Bike", "Petrol", "Kawasaki", "Z1000", "2003", "2020"),
  r("Bike", "Petrol", "Kawasaki", "Z H2", "2020", "~"),
  r("Bike", "Petrol", "Kawasaki", "Versys 650", "2007", "~"),
  r("Bike", "Petrol", "Kawasaki", "Versys 1000", "2012", "~"),
  r("Bike", "Petrol", "Kawasaki", "KLX 230", "2020", "~"),
  r("Bike", "Petrol", "Kawasaki", "KX 450", "1974", "~"),
  // Suzuki
  r("Bike", "Petrol", "Suzuki", "GSX-R150", "2017", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-S150", "2017", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-R600", "1997", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-R750", "1985", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-R1000", "2001", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-S1000", "2015", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-8S", "2023", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-8R", "2024", "~"),
  r("Bike", "Petrol", "Suzuki", "Hayabusa", "1999", "~"),
  r("Bike", "Petrol", "Suzuki", "V-Strom 250", "2017", "~"),
  r("Bike", "Petrol", "Suzuki", "V-Strom 650", "2004", "~"),
  r("Bike", "Petrol", "Suzuki", "V-Strom 1050", "2019", "~"),
  r("Bike", "Petrol", "Suzuki", "Katana", "1981", "~"),
  // Ducati
  r("Bike", "Petrol", "Ducati", "Panigale V2", "2020", "~"),
  r("Bike", "Petrol", "Ducati", "Panigale V4", "2018", "~"),
  r("Bike", "Petrol", "Ducati", "Panigale V4 R", "2019", "~"),
  r("Bike", "Petrol", "Ducati", "Monster", "1993", "~"),
  r("Bike", "Petrol", "Ducati", "Monster SP", "2023", "~"),
  r("Bike", "Petrol", "Ducati", "Streetfighter V2", "2022", "~"),
  r("Bike", "Petrol", "Ducati", "Streetfighter V4", "2020", "~"),
  r("Bike", "Petrol", "Ducati", "Multistrada V2", "2022", "~"),
  r("Bike", "Petrol", "Ducati", "Multistrada V4", "2021", "~"),
  r("Bike", "Petrol", "Ducati", "Diavel V4", "2023", "~"),
  r("Bike", "Petrol", "Ducati", "XDiavel", "2016", "~"),
  r("Bike", "Petrol", "Ducati", "Scrambler", "2015", "~"),
  r("Bike", "Petrol", "Ducati", "DesertX", "2022", "~"),
  r("Bike", "Petrol", "Ducati", "Hypermotard 950", "2019", "~"),
  // Harley-Davidson
  r("Bike", "Petrol", "Harley-Davidson", "Iron 883", "2009", "2022"),
  r("Bike", "Petrol", "Harley-Davidson", "Forty-Eight", "2010", "2022"),
  r("Bike", "Petrol", "Harley-Davidson", "Sportster S", "2021", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "Nightster", "2022", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "Street 750", "2014", "2021"),
  r("Bike", "Petrol", "Harley-Davidson", "Street Glide", "2006", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "Road Glide", "1998", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "Road King", "1994", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "Fat Boy", "1990", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "Heritage Classic", "1986", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "Pan America 1250", "2021", "~"),
  r("Bike", "Petrol", "Harley-Davidson", "CVO Street Glide", "2010", "~"),
  r("Bike", "EV", "Harley-Davidson", "LiveWire", "2019", "2021"),
  // BMW Motorrad
  r("Bike", "Petrol", "BMW", "G 310 R", "2016", "~"),
  r("Bike", "Petrol", "BMW", "G 310 GS", "2017", "~"),
  r("Bike", "Petrol", "BMW", "F 750 GS", "2018", "2023"),
  r("Bike", "Petrol", "BMW", "F 850 GS", "2018", "~"),
  r("Bike", "Petrol", "BMW", "F 900 R", "2020", "~"),
  r("Bike", "Petrol", "BMW", "F 900 XR", "2020", "~"),
  r("Bike", "Petrol", "BMW", "R 1250 GS", "2018", "2023"),
  r("Bike", "Petrol", "BMW", "R 1250 GS Adventure", "2018", "2023"),
  r("Bike", "Petrol", "BMW", "R 1300 GS", "2024", "~"),
  r("Bike", "Petrol", "BMW", "S 1000 RR", "2009", "~"),
  r("Bike", "Petrol", "BMW", "M 1000 RR", "2020", "~"),
  r("Bike", "Petrol", "BMW", "S 1000 R", "2014", "~"),
  r("Bike", "Petrol", "BMW", "S 1000 XR", "2015", "~"),
  r("Bike", "Petrol", "BMW", "R nineT", "2014", "~"),
  r("Bike", "Petrol", "BMW", "K 1600 GTL", "2011", "~"),
  // KTM
  r("Bike", "Petrol", "KTM", "Duke 125", "2011", "~"),
  r("Bike", "Petrol", "KTM", "Duke 200", "2012", "~"),
  r("Bike", "Petrol", "KTM", "Duke 250", "2017", "~"),
  r("Bike", "Petrol", "KTM", "Duke 390", "2013", "~"),
  r("Bike", "Petrol", "KTM", "Duke 790", "2018", "~"),
  r("Bike", "Petrol", "KTM", "Duke 890", "2020", "~"),
  r("Bike", "Petrol", "KTM", "RC 125", "2014", "~"),
  r("Bike", "Petrol", "KTM", "RC 390", "2014", "~"),
  r("Bike", "Petrol", "KTM", "1290 Super Duke R", "2014", "~"),
  r("Bike", "Petrol", "KTM", "1290 Super Adventure", "2015", "~"),
  r("Bike", "Petrol", "KTM", "390 Adventure", "2020", "~"),
  // Aprilia
  r("Bike", "Petrol", "Aprilia", "RS 125", "1992", "~"),
  r("Bike", "Petrol", "Aprilia", "RS 660", "2021", "~"),
  r("Bike", "Petrol", "Aprilia", "Tuono 660", "2021", "~"),
  r("Bike", "Petrol", "Aprilia", "Tuono V4", "2011", "~"),
  r("Bike", "Petrol", "Aprilia", "RSV4", "2009", "~"),
  r("Bike", "Petrol", "Aprilia", "Tuareg 660", "2022", "~"),
  // Triumph / MV / Norton
  r("Bike", "Petrol", "Triumph", "Bonneville T100", "2002", "~"),
  r("Bike", "Petrol", "Triumph", "Bonneville T120", "2016", "~"),
  r("Bike", "Petrol", "Triumph", "Speed Twin", "2019", "~"),
  r("Bike", "Petrol", "Triumph", "Speed 400", "2023", "~"),
  r("Bike", "Petrol", "Triumph", "Scrambler 400 X", "2024", "~"),
  r("Bike", "Petrol", "Triumph", "Street Triple", "2007", "~"),
  r("Bike", "Petrol", "Triumph", "Street Triple RS", "2017", "~"),
  r("Bike", "Petrol", "Triumph", "Speed Triple 1200 RS", "2021", "~"),
  r("Bike", "Petrol", "Triumph", "Speed Triple 1200 RR", "2022", "~"),
  r("Bike", "Petrol", "Triumph", "Tiger 660 Sport", "2021", "~"),
  r("Bike", "Petrol", "Triumph", "Tiger 900", "2020", "~"),
  r("Bike", "Petrol", "Triumph", "Tiger 1200", "2012", "~"),
  r("Bike", "Petrol", "Triumph", "Daytona 660", "2024", "~"),
  r("Bike", "Petrol", "Triumph", "Rocket 3", "2004", "~"),
  r("Bike", "Petrol", "MV Agusta", "F3 800", "2014", "~"),
  r("Bike", "Petrol", "MV Agusta", "Brutale 1000 RR", "2020", "~"),
  r("Bike", "Petrol", "MV Agusta", "Dragster 800 RR", "2018", "~"),
  r("Bike", "Petrol", "Norton", "V4SV", "2022", "~"),
  r("Bike", "Petrol", "Norton", "Commando 961", "2023", "~"),
  // Modenas / SYM / Benelli / Kymco / CFMOTO
  r("Bike", "Petrol", "Modenas", "Kriss 110", "1996", "~"),
  r("Bike", "Petrol", "Modenas", "Karisma", "2006", "2018"),
  r("Bike", "Petrol", "Modenas", "Pulsar NS200", "2014", "~"),
  r("Bike", "Petrol", "Modenas", "Pulsar RS200", "2015", "~"),
  r("Bike", "Petrol", "Modenas", "Dominar 400", "2017", "~"),
  r("Bike", "Petrol", "SYM", "Sport Rider 125i", "2014", "~"),
  r("Bike", "Petrol", "Benelli", "TNT 135", "2017", "~"),
  r("Bike", "Petrol", "Benelli", "TRK 251", "2020", "~"),
  r("Bike", "Petrol", "Benelli", "TRK 502", "2017", "~"),
  r("Bike", "Petrol", "Benelli", "TRK 702", "2024", "~"),
  r("Bike", "Petrol", "Benelli", "TNT 600i", "2014", "~"),
  r("Bike", "Petrol", "Benelli", "Leoncino 500", "2017", "~"),
  r("Bike", "Petrol", "CFMOTO", "300NK", "2018", "~"),
  r("Bike", "Petrol", "CFMOTO", "650NK", "2012", "~"),
  r("Bike", "Petrol", "CFMOTO", "700CL-X", "2021", "~"),
  r("Bike", "Petrol", "CFMOTO", "800MT", "2021", "~"),
  r("Bike", "Petrol", "CFMOTO", "450SR", "2023", "~"),
  // Royal Enfield / Bajaj / TVS / Hero
  r("Bike", "Petrol", "Royal Enfield", "Bullet 350", "1948", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Classic 350", "2009", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Hunter 350", "2022", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Meteor 350", "2020", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Himalayan", "2016", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Himalayan 450", "2023", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Continental GT 650", "2018", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Interceptor 650", "2018", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Super Meteor 650", "2023", "~"),
  r("Bike", "Petrol", "Bajaj", "Pulsar 150", "2001", "~"),
  r("Bike", "Petrol", "Bajaj", "Pulsar NS200", "2012", "~"),
  r("Bike", "Petrol", "Bajaj", "Dominar 400", "2017", "~"),
  r("Bike", "Petrol", "TVS", "Apache RTR 200", "2016", "~"),
  r("Bike", "Petrol", "TVS", "Apache RR 310", "2018", "~"),
  r("Bike", "Petrol", "Hero", "Splendor Plus", "1994", "~"),
  r("Bike", "Petrol", "Hero", "Xpulse 200", "2019", "~"),
  // EV Bikes
  r("Bike", "EV", "Zero Motorcycles", "S", "2009", "~"),
  r("Bike", "EV", "Zero Motorcycles", "DSR", "2015", "~"),
  r("Bike", "EV", "Zero Motorcycles", "SR/F", "2019", "~"),
  r("Bike", "EV", "Zero Motorcycles", "SR/S", "2020", "~"),
  r("Bike", "EV", "Energica", "Ego", "2014", "~"),
  r("Bike", "EV", "Energica", "Eva Ribelle", "2019", "~"),
  r("Bike", "EV", "Energica", "Experia", "2022", "~"),
  r("Bike", "EV", "LiveWire", "One", "2021", "~"),
  r("Bike", "EV", "LiveWire", "S2 Del Mar", "2024", "~"),
  r("Bike", "EV", "Davinci", "DC100", "2022", "~"),
  r("Bike", "EV", "CAKE", "Kalk OR", "2018", "~"),
  r("Bike", "EV", "Damon", "HyperSport", "2024", "~"),
  r("Bike", "EV", "Verge", "TS Ultra", "2023", "~"),
];

// ---------------- SCOOTER ----------------
const SCOOTER: R[] = [
  r("Scooter", "Petrol", "Yamaha", "Mio", "2003", "~"),
  r("Scooter", "Petrol", "Yamaha", "NMAX 155", "2015", "~"),
  r("Scooter", "Petrol", "Yamaha", "Aerox 155", "2016", "~"),
  r("Scooter", "Petrol", "Yamaha", "XMAX 250", "2017", "~"),
  r("Scooter", "Petrol", "Yamaha", "XMAX 300", "2017", "~"),
  r("Scooter", "Petrol", "Yamaha", "TMAX 560", "2020", "~"),
  r("Scooter", "Petrol", "Honda", "BeAT", "2008", "~"),
  r("Scooter", "Petrol", "Honda", "Vario 125", "2014", "~"),
  r("Scooter", "Petrol", "Honda", "Vario 160", "2022", "~"),
  r("Scooter", "Petrol", "Honda", "ADV 160", "2022", "~"),
  r("Scooter", "Petrol", "Honda", "PCX 125", "2009", "~"),
  r("Scooter", "Petrol", "Honda", "PCX 160", "2021", "~"),
  r("Scooter", "Petrol", "Honda", "Forza 250", "2008", "~"),
  r("Scooter", "Petrol", "Honda", "Forza 350", "2020", "~"),
  r("Scooter", "Petrol", "Honda", "Forza 750", "2021", "~"),
  r("Scooter", "Petrol", "Honda", "X-ADV 750", "2017", "~"),
  r("Scooter", "Petrol", "Vespa", "Primavera 150", "2014", "~"),
  r("Scooter", "Petrol", "Vespa", "Sprint 150", "2014", "~"),
  r("Scooter", "Petrol", "Vespa", "GTS 300", "2017", "~"),
  r("Scooter", "Petrol", "Vespa", "GTS 300 HPE", "2019", "~"),
  r("Scooter", "Petrol", "SYM", "Cruisym 250", "2017", "~"),
  r("Scooter", "Petrol", "SYM", "Maxsym TL 500", "2020", "~"),
  r("Scooter", "Petrol", "SYM", "Joymax Z 300", "2020", "~"),
  r("Scooter", "Petrol", "Kymco", "AK 550", "2017", "~"),
  r("Scooter", "Petrol", "Kymco", "Xciting S 400", "2018", "~"),
  r("Scooter", "Petrol", "Kymco", "DTX 360", "2022", "~"),
  r("Scooter", "Petrol", "Piaggio", "Beverly 400", "2021", "~"),
  r("Scooter", "Petrol", "Piaggio", "MP3 530", "2022", "~"),
  r("Scooter", "Petrol", "Suzuki", "Burgman 400", "2007", "~"),
  r("Scooter", "EV", "Niu", "NQi GTS", "2018", "~"),
  r("Scooter", "EV", "Niu", "MQi GT", "2020", "~"),
  r("Scooter", "EV", "Niu", "RQi", "2021", "~"),
  r("Scooter", "EV", "Gogoro", "Smartscooter 2", "2017", "~"),
  r("Scooter", "EV", "Gogoro", "Pulse", "2024", "~"),
  r("Scooter", "EV", "Vespa", "Elettrica", "2019", "~"),
  r("Scooter", "EV", "BMW", "CE 04", "2022", "~"),
  r("Scooter", "EV", "BMW", "CE 02", "2024", "~"),
  r("Scooter", "EV", "Silence", "S01", "2020", "~"),
  r("Scooter", "EV", "Super Soco", "CPx", "2020", "~"),
  r("Scooter", "EV", "Yadea", "G5", "2019", "~"),
  r("Scooter", "EV", "Ola Electric", "S1 Pro", "2021", "~"),
  r("Scooter", "EV", "Ather", "450X", "2020", "~"),
  r("Scooter", "EV", "TVS", "iQube", "2020", "~"),
  r("Scooter", "EV", "Bajaj", "Chetak Electric", "2020", "~"),
];

// ---------------- AUTO RICKSHAW ----------------
const AUTO: R[] = [
  r("Auto Rickshaw", "Petrol", "Bajaj", "RE Compact", "1959", "~"),
  r("Auto Rickshaw", "CNG", "Bajaj", "RE Compact CNG", "2005", "~"),
  r("Auto Rickshaw", "EV", "Bajaj", "RE EV", "2022", "~"),
  r("Auto Rickshaw", "Petrol", "Bajaj", "Maxima Z", "2014", "~"),
  r("Auto Rickshaw", "Petrol", "TVS", "King Deluxe", "2010", "~"),
  r("Auto Rickshaw", "CNG", "TVS", "King Duramax", "2014", "~"),
  r("Auto Rickshaw", "EV", "Mahindra", "Treo", "2018", "~"),
  r("Auto Rickshaw", "EV", "Mahindra", "Treo Yaari", "2019", "~"),
  r("Auto Rickshaw", "EV", "Mahindra", "Zor Grand", "2022", "~"),
  r("Auto Rickshaw", "EV", "Piaggio", "Ape E-City", "2019", "~"),
  r("Auto Rickshaw", "Petrol", "Piaggio", "Ape Auto", "1948", "~"),
  r("Auto Rickshaw", "Diesel", "Piaggio", "Ape Xtra LDX", "2014", "~"),
  r("Auto Rickshaw", "EV", "Atul", "Elite Plus", "2018", "~"),
  r("Auto Rickshaw", "EV", "YC Electric", "Yatri Super", "2018", "~"),
];

// ---------------- KEI / MICRO CAR ----------------
const KEI: R[] = [
  r("Kei Car", "Petrol", "Suzuki", "Wagon R", "1993", "~"),
  r("Kei Car", "Hybrid", "Suzuki", "Wagon R Hybrid", "2017", "~"),
  r("Kei Car", "Petrol", "Suzuki", "Alto Lapin", "2002", "~"),
  r("Kei Car", "Petrol", "Suzuki", "Hustler", "2014", "~"),
  r("Kei Car", "Petrol", "Suzuki", "Spacia", "2013", "~"),
  r("Kei Car", "Petrol", "Suzuki", "Jimny", "1970", "~"),
  r("Kei Car", "Petrol", "Daihatsu", "Move", "1995", "~"),
  r("Kei Car", "Petrol", "Daihatsu", "Tanto", "2003", "~"),
  r("Kei Car", "Petrol", "Daihatsu", "Mira e:S", "2011", "~"),
  r("Kei Car", "Petrol", "Daihatsu", "Copen", "2002", "~"),
  r("Kei Car", "Petrol", "Honda", "N-Box", "2011", "~"),
  r("Kei Car", "Petrol", "Honda", "N-One", "2012", "~"),
  r("Kei Car", "Petrol", "Honda", "N-WGN", "2013", "~"),
  r("Kei Car", "EV", "Honda", "N-Van e:", "2024", "~"),
  r("Kei Car", "Petrol", "Mitsubishi", "eK Wagon", "2001", "~"),
  r("Kei Car", "EV", "Mitsubishi", "eK X EV", "2022", "~"),
  r("Kei Car", "Petrol", "Nissan", "Dayz", "2013", "~"),
  r("Kei Car", "EV", "Nissan", "Sakura", "2022", "~"),
  r("Kei Car", "EV", "Wuling", "Hongguang Mini EV", "2020", "~"),
];

// ---------------- BICYCLE / E-BIKE ----------------
const BICYCLE: R[] = [
  r("Bicycle", "Manual", "Trek", "Madone SLR", "2003", "~"),
  r("Bicycle", "Manual", "Trek", "Domane SLR", "2012", "~"),
  r("Bicycle", "Manual", "Trek", "Emonda SLR", "2014", "~"),
  r("Bicycle", "Manual", "Specialized", "Tarmac SL8", "2023", "~"),
  r("Bicycle", "Manual", "Specialized", "Roubaix SL8", "2023", "~"),
  r("Bicycle", "Manual", "Specialized", "Allez", "1981", "~"),
  r("Bicycle", "Manual", "Giant", "TCR Advanced SL", "1998", "~"),
  r("Bicycle", "Manual", "Giant", "Defy Advanced", "2008", "~"),
  r("Bicycle", "Manual", "Giant", "Propel Advanced SL", "2013", "~"),
  r("Bicycle", "Manual", "Cannondale", "SuperSix EVO", "2008", "~"),
  r("Bicycle", "Manual", "Cannondale", "Synapse Carbon", "2006", "~"),
  r("Bicycle", "Manual", "Cervelo", "S5", "2010", "~"),
  r("Bicycle", "Manual", "Cervelo", "R5", "2008", "~"),
  r("Bicycle", "Manual", "Pinarello", "Dogma F", "2022", "~"),
  r("Bicycle", "Manual", "Bianchi", "Oltre RC", "2022", "~"),
  r("Bicycle", "Manual", "Canyon", "Aeroad CFR", "2014", "~"),
  r("Bicycle", "Manual", "Canyon", "Ultimate CFR", "2020", "~"),
  r("Bicycle", "Manual", "Brompton", "C Line", "1976", "~"),
  r("Bicycle", "EV", "Brompton", "Electric P Line", "2022", "~"),
  r("Bicycle", "EV", "Specialized", "Turbo Vado SL", "2020", "~"),
  r("Bicycle", "EV", "Specialized", "Turbo Levo", "2015", "~"),
  r("Bicycle", "EV", "Trek", "Domane+ SLR", "2022", "~"),
  r("Bicycle", "EV", "Trek", "Rail 9.9", "2019", "~"),
  r("Bicycle", "EV", "Giant", "Trance X E+", "2020", "~"),
  r("Bicycle", "EV", "Cannondale", "Topstone Neo", "2020", "~"),
  r("Bicycle", "EV", "VanMoof", "S5", "2022", "~"),
  r("Bicycle", "EV", "VanMoof", "A5", "2022", "~"),
  r("Bicycle", "EV", "Cowboy", "4", "2022", "~"),
  r("Bicycle", "EV", "Rad Power", "RadRunner 3 Plus", "2022", "~"),
  r("Bicycle", "EV", "Rad Power", "RadRover 6 Plus", "2021", "~"),
  r("Bicycle", "EV", "Riese & Müller", "Charger4", "2022", "~"),
  r("Bicycle", "EV", "Tern", "GSD S10", "2018", "~"),
  r("Bicycle", "EV", "Yamaha", "Wabash RT", "2022", "~"),
];

// ---------------- LATEST 2024 - 2026 ----------------
// Recently launched / refreshed / announced vehicles across global markets,
// including the freshest EVs, hybrids, and ICE nameplates as of 2026.
const LATEST: R[] = [
  // --- Tesla ---
  r("Pickup", "EV", "Tesla", "Cybertruck", "2023", "~"),
  r("Pickup", "EV", "Tesla", "Cybertruck Cyberbeast", "2024", "~"),
  r("Sedan", "EV", "Tesla", "Model 3 Highland", "2023", "~"),
  r("Sedan", "EV", "Tesla", "Model 3 Performance (Ludicrous)", "2024", "~"),
  r("SUV", "EV", "Tesla", "Model Y Juniper", "2025", "~"),
  r("Sedan", "EV", "Tesla", "Model S Plaid Refresh", "2025", "~"),
  r("SUV", "EV", "Tesla", "Model X Plaid Refresh", "2025", "~"),
  r("Hatchback", "EV", "Tesla", "Model 2 / Affordable EV", "2026", "~"),
  r("MPV", "EV", "Tesla", "Robovan", "2026", "~"),
  r("Coupe", "EV", "Tesla", "Cybercab", "2026", "~"),
  r("Coupe", "EV", "Tesla", "Roadster (2nd Gen)", "2026", "~"),

  // --- BYD ---
  r("Sedan", "EV", "BYD", "Seal", "2022", "~"),
  r("Sedan", "PHEV", "BYD", "Seal DM-i", "2024", "~"),
  r("SUV", "EV", "BYD", "Atto 3", "2022", "~"),
  r("SUV", "EV", "BYD", "Atto 2", "2024", "~"),
  r("Hatchback", "EV", "BYD", "Dolphin", "2021", "~"),
  r("Hatchback", "EV", "BYD", "Seagull / Dolphin Mini", "2023", "~"),
  r("SUV", "EV", "BYD", "Sealion 7", "2024", "~"),
  r("SUV", "PHEV", "BYD", "Sealion 6 DM-i", "2024", "~"),
  r("Sedan", "EV", "BYD", "Han EV (2025 Refresh)", "2025", "~"),
  r("SUV", "EV", "BYD", "Tang EV (2025 Refresh)", "2025", "~"),
  r("Pickup", "PHEV", "BYD", "Shark 6", "2024", "~"),
  r("SUV", "PHEV", "BYD", "Yangwang U8", "2023", "~"),
  r("Coupe", "EV", "BYD", "Yangwang U9", "2024", "~"),
  r("SUV", "EV", "BYD", "Denza N9", "2025", "~"),
  r("MPV", "EV", "BYD", "Denza D9 EV", "2022", "~"),

  // --- Xpeng / Nio / Li Auto / Zeekr / Xiaomi ---
  r("Sedan", "EV", "Xpeng", "P7+", "2024", "~"),
  r("SUV", "EV", "Xpeng", "G6", "2023", "~"),
  r("SUV", "EV", "Xpeng", "G9 (2025)", "2025", "~"),
  r("MPV", "EV", "Xpeng", "X9", "2024", "~"),
  r("Hatchback", "EV", "Xpeng", "Mona M03", "2024", "~"),
  r("Sedan", "EV", "Nio", "ET9", "2025", "~"),
  r("Sedan", "EV", "Nio", "ET5 (2025)", "2025", "~"),
  r("SUV", "EV", "Nio", "EL8 / ES8 (2024)", "2024", "~"),
  r("Hatchback", "EV", "Nio", "Onvo L60", "2024", "~"),
  r("SUV", "EV", "Nio", "Onvo L90", "2025", "~"),
  r("Hatchback", "EV", "Nio", "Firefly", "2025", "~"),
  r("SUV", "PHEV", "Li Auto", "L6", "2024", "~"),
  r("SUV", "PHEV", "Li Auto", "L7", "2022", "~"),
  r("SUV", "PHEV", "Li Auto", "L9", "2022", "~"),
  r("MPV", "EV", "Li Auto", "Mega", "2024", "~"),
  r("Sedan", "EV", "Zeekr", "007", "2024", "~"),
  r("SUV", "EV", "Zeekr", "7X", "2024", "~"),
  r("MPV", "EV", "Zeekr", "009", "2022", "~"),
  r("Hatchback", "EV", "Zeekr", "X", "2023", "~"),
  r("Hatchback", "EV", "Zeekr", "001 FR", "2024", "~"),
  r("Sedan", "EV", "Xiaomi", "SU7", "2024", "~"),
  r("Sedan", "EV", "Xiaomi", "SU7 Ultra", "2025", "~"),
  r("SUV", "EV", "Xiaomi", "YU7", "2025", "~"),

  // --- Toyota / Lexus ---
  r("SUV", "Hybrid", "Toyota", "Land Cruiser 250 / Prado (2024)", "2024", "~"),
  r("SUV", "Hybrid", "Toyota", "4Runner (6th Gen)", "2024", "~"),
  r("SUV", "Hybrid", "Toyota", "Crown Signia", "2024", "~"),
  r("Sedan", "Hybrid", "Toyota", "Camry (9th Gen)", "2024", "~"),
  r("Hatchback", "Hybrid", "Toyota", "Prius (5th Gen)", "2023", "~"),
  r("SUV", "EV", "Toyota", "bZ4X (2025)", "2025", "~"),
  r("SUV", "EV", "Toyota", "bZ3X", "2025", "~"),
  r("SUV", "EV", "Toyota", "Urban Cruiser EV", "2025", "~"),
  r("Pickup", "Hybrid", "Toyota", "Tacoma (4th Gen)", "2024", "~"),
  r("Pickup", "Hybrid", "Toyota", "Tundra i-Force MAX", "2022", "~"),
  r("SUV", "Hybrid", "Lexus", "GX 550", "2024", "~"),
  r("SUV", "Hybrid", "Lexus", "TX", "2024", "~"),
  r("SUV", "EV", "Lexus", "RZ 450e (2025)", "2025", "~"),
  r("Sedan", "Hybrid", "Lexus", "LS (2025)", "2025", "~"),
  r("Coupe", "EV", "Lexus", "LF-ZC", "2026", "~"),

  // --- Honda / Acura ---
  r("SUV", "EV", "Honda", "Prologue", "2024", "~"),
  r("SUV", "EV", "Honda", "e:NY1", "2023", "~"),
  r("SUV", "Hybrid", "Honda", "CR-V (6th Gen)", "2023", "~"),
  r("SUV", "Hybrid", "Honda", "Passport (4th Gen)", "2025", "~"),
  r("Sedan", "Hybrid", "Honda", "Civic (2025 Refresh)", "2025", "~"),
  r("Sedan", "EV", "Honda", "0 Saloon", "2026", "~"),
  r("SUV", "EV", "Honda", "0 SUV", "2026", "~"),
  r("SUV", "EV", "Acura", "ZDX", "2024", "~"),
  r("SUV", "Hybrid", "Acura", "MDX (2025)", "2025", "~"),

  // --- Hyundai / Kia / Genesis ---
  r("SUV", "EV", "Hyundai", "Ioniq 5 N", "2024", "~"),
  r("SUV", "EV", "Hyundai", "Ioniq 5 (2025 Refresh)", "2025", "~"),
  r("SUV", "EV", "Hyundai", "Ioniq 9", "2025", "~"),
  r("Sedan", "EV", "Hyundai", "Ioniq 6 (2025)", "2025", "~"),
  r("SUV", "Hybrid", "Hyundai", "Santa Fe (5th Gen)", "2024", "~"),
  r("SUV", "Hybrid", "Hyundai", "Tucson (2025 Refresh)", "2025", "~"),
  r("Hatchback", "EV", "Hyundai", "Inster", "2024", "~"),
  r("SUV", "Hybrid", "Kia", "Sorento (2024)", "2024", "~"),
  r("SUV", "EV", "Kia", "EV3", "2024", "~"),
  r("SUV", "EV", "Kia", "EV5", "2023", "~"),
  r("SUV", "EV", "Kia", "EV9", "2023", "~"),
  r("Sedan", "EV", "Kia", "EV4", "2025", "~"),
  r("MPV", "EV", "Kia", "PV5", "2025", "~"),
  r("SUV", "EV", "Kia", "EV6 (2025 Refresh)", "2025", "~"),
  r("SUV", "Hybrid", "Kia", "K4 / K3 Sedan", "2024", "~"),
  r("SUV", "EV", "Genesis", "GV60 (2025)", "2025", "~"),
  r("SUV", "EV", "Genesis", "GV70 Electrified (2025)", "2025", "~"),
  r("Sedan", "EV", "Genesis", "G80 Electrified (2025)", "2025", "~"),
  r("Coupe", "EV", "Genesis", "X Gran Coupe", "2026", "~"),

  // --- Volkswagen Group ---
  r("SUV", "EV", "Volkswagen", "ID.7 Tourer", "2024", "~"),
  r("Sedan", "EV", "Volkswagen", "ID.7", "2023", "~"),
  r("Hatchback", "EV", "Volkswagen", "ID.3 (2024 Refresh)", "2024", "~"),
  r("SUV", "EV", "Volkswagen", "ID.4 (2025)", "2025", "~"),
  r("SUV", "EV", "Volkswagen", "ID.Buzz LWB", "2024", "~"),
  r("Hatchback", "EV", "Volkswagen", "ID.2all", "2026", "~"),
  r("SUV", "PHEV", "Volkswagen", "Tiguan (3rd Gen)", "2024", "~"),
  r("SUV", "PHEV", "Volkswagen", "Tayron", "2024", "~"),
  r("Sedan", "EV", "Audi", "A6 e-tron", "2024", "~"),
  r("SUV", "EV", "Audi", "Q6 e-tron", "2024", "~"),
  r("SUV", "EV", "Audi", "Q4 e-tron (2025)", "2025", "~"),
  r("Sedan", "EV", "Audi", "e-tron GT (2025 Refresh)", "2025", "~"),
  r("SUV", "EV", "Audi", "Q8 e-tron (2024)", "2024", "~"),
  r("SUV", "EV", "Porsche", "Macan EV", "2024", "~"),
  r("Sedan", "EV", "Porsche", "Taycan (2024 Refresh)", "2024", "~"),
  r("SUV", "EV", "Porsche", "Cayenne EV", "2026", "~"),
  r("Coupe", "Hybrid", "Porsche", "911 GTS T-Hybrid", "2024", "~"),
  r("SUV", "EV", "Skoda", "Elroq", "2024", "~"),
  r("SUV", "EV", "Skoda", "Enyaq (2025 Refresh)", "2025", "~"),
  r("SUV", "EV", "Cupra", "Tavascan", "2024", "~"),
  r("Hatchback", "EV", "Cupra", "Born VZ", "2024", "~"),

  // --- BMW / Mini ---
  r("SUV", "EV", "BMW", "iX2", "2024", "~"),
  r("Sedan", "EV", "BMW", "i5", "2023", "~"),
  r("Wagon", "EV", "BMW", "i5 Touring", "2024", "~"),
  r("SUV", "EV", "BMW", "iX3 (Neue Klasse)", "2025", "~"),
  r("Sedan", "EV", "BMW", "i3 (Neue Klasse Sedan)", "2026", "~"),
  r("SUV", "PHEV", "BMW", "X3 (G45)", "2024", "~"),
  r("Sedan", "PHEV", "BMW", "5 Series (G60)", "2023", "~"),
  r("Coupe", "Petrol", "BMW", "M5 Touring (G99)", "2024", "~"),
  r("SUV", "EV", "Mini", "Countryman E", "2024", "~"),
  r("Hatchback", "EV", "Mini", "Cooper E (J01)", "2024", "~"),
  r("Hatchback", "EV", "Mini", "Aceman", "2024", "~"),

  // --- Mercedes-Benz ---
  r("SUV", "EV", "Mercedes-Benz", "EQG / G-Class Electric", "2024", "~"),
  r("Sedan", "EV", "Mercedes-Benz", "CLA EV", "2025", "~"),
  r("SUV", "EV", "Mercedes-Benz", "GLC EV", "2026", "~"),
  r("Sedan", "PHEV", "Mercedes-Benz", "E-Class (W214)", "2024", "~"),
  r("Coupe", "Petrol", "Mercedes-Benz", "AMG GT (C192)", "2024", "~"),
  r("SUV", "EV", "Mercedes-Benz", "EQS SUV (2025 Refresh)", "2025", "~"),

  // --- Volvo / Polestar ---
  r("SUV", "EV", "Volvo", "EX30", "2024", "~"),
  r("SUV", "EV", "Volvo", "EX90", "2024", "~"),
  r("MPV", "EV", "Volvo", "EM90", "2024", "~"),
  r("SUV", "EV", "Volvo", "EX60", "2026", "~"),
  r("Sedan", "EV", "Polestar", "2 (2024 Refresh)", "2024", "~"),
  r("SUV", "EV", "Polestar", "3", "2024", "~"),
  r("SUV", "EV", "Polestar", "4", "2024", "~"),
  r("Sedan", "EV", "Polestar", "5", "2025", "~"),
  r("SUV", "EV", "Polestar", "6 Roadster", "2026", "~"),

  // --- Stellantis (Jeep / Ram / Dodge / Fiat / Alfa / Maserati / Citroen / Peugeot) ---
  r("SUV", "EV", "Jeep", "Wagoneer S", "2024", "~"),
  r("SUV", "EV", "Jeep", "Recon", "2025", "~"),
  r("SUV", "EV", "Jeep", "Avenger", "2023", "~"),
  r("Pickup", "EV", "Ram", "1500 REV", "2025", "~"),
  r("Pickup", "PHEV", "Ram", "1500 Ramcharger", "2025", "~"),
  r("Coupe", "EV", "Dodge", "Charger Daytona", "2024", "~"),
  r("Sedan", "Petrol", "Dodge", "Charger Sixpack", "2025", "~"),
  r("Hatchback", "EV", "Fiat", "600e", "2024", "~"),
  r("Hatchback", "EV", "Fiat", "Grande Panda", "2024", "~"),
  r("SUV", "EV", "Alfa Romeo", "Junior (Milano)", "2024", "~"),
  r("SUV", "EV", "Maserati", "Grecale Folgore", "2024", "~"),
  r("Coupe", "EV", "Maserati", "GranTurismo Folgore", "2024", "~"),
  r("SUV", "EV", "Citroen", "e-C3", "2024", "~"),
  r("SUV", "EV", "Citroen", "C3 Aircross EV", "2024", "~"),
  r("SUV", "EV", "Peugeot", "e-3008", "2024", "~"),
  r("SUV", "EV", "Peugeot", "e-5008", "2024", "~"),

  // --- Renault / Dacia ---
  r("Hatchback", "EV", "Renault", "5 E-Tech", "2024", "~"),
  r("Hatchback", "EV", "Renault", "4 E-Tech", "2025", "~"),
  r("SUV", "EV", "Renault", "Scenic E-Tech", "2024", "~"),
  r("SUV", "Hybrid", "Renault", "Rafale", "2024", "~"),
  r("Hatchback", "EV", "Dacia", "Spring (2024 Refresh)", "2024", "~"),
  r("SUV", "Hybrid", "Dacia", "Bigster", "2025", "~"),
  r("SUV", "Hybrid", "Dacia", "Duster (3rd Gen)", "2024", "~"),

  // --- Nissan / Mitsubishi / Subaru ---
  r("SUV", "Hybrid", "Nissan", "Kicks (3rd Gen)", "2024", "~"),
  r("SUV", "Hybrid", "Nissan", "Murano (4th Gen)", "2025", "~"),
  r("SUV", "EV", "Nissan", "Ariya Nismo", "2024", "~"),
  r("Hatchback", "EV", "Nissan", "Leaf (3rd Gen)", "2025", "~"),
  r("SUV", "PHEV", "Mitsubishi", "Outlander PHEV (2024 Refresh)", "2024", "~"),
  r("Pickup", "Diesel", "Mitsubishi", "Triton (6th Gen)", "2024", "~"),
  r("SUV", "EV", "Subaru", "Trailseeker", "2025", "~"),
  r("SUV", "Hybrid", "Subaru", "Forester (6th Gen)", "2025", "~"),
  r("SUV", "Hybrid", "Subaru", "Crosstrek Hybrid", "2026", "~"),

  // --- Mazda / Suzuki ---
  r("SUV", "PHEV", "Mazda", "CX-70", "2024", "~"),
  r("SUV", "PHEV", "Mazda", "CX-80", "2024", "~"),
  r("Coupe", "Petrol", "Mazda", "Iconic SP", "2026", "~"),
  r("SUV", "EV", "Mazda", "6e", "2025", "~"),
  r("SUV", "EV", "Suzuki", "e Vitara", "2025", "~"),
  r("Hatchback", "Hybrid", "Suzuki", "Swift (4th Gen)", "2024", "~"),

  // --- Ford / GM / Lincoln / Cadillac / GMC ---
  r("Pickup", "Hybrid", "Ford", "F-150 (2024 Refresh)", "2024", "~"),
  r("Pickup", "EV", "Ford", "F-150 Lightning (2025)", "2025", "~"),
  r("SUV", "PHEV", "Ford", "Explorer EV (Europe)", "2024", "~"),
  r("SUV", "EV", "Ford", "Capri EV", "2024", "~"),
  r("SUV", "Hybrid", "Ford", "Bronco Sport (2025)", "2025", "~"),
  r("SUV", "EV", "Cadillac", "Lyriq (2025)", "2025", "~"),
  r("SUV", "EV", "Cadillac", "Escalade IQ", "2025", "~"),
  r("SUV", "EV", "Cadillac", "Optiq", "2025", "~"),
  r("SUV", "EV", "Cadillac", "Vistiq", "2026", "~"),
  r("Sedan", "EV", "Cadillac", "Celestiq", "2024", "~"),
  r("SUV", "EV", "Chevrolet", "Equinox EV", "2024", "~"),
  r("SUV", "EV", "Chevrolet", "Blazer EV (2025)", "2025", "~"),
  r("Pickup", "EV", "Chevrolet", "Silverado EV", "2024", "~"),
  r("Pickup", "EV", "GMC", "Sierra EV", "2024", "~"),
  r("SUV", "EV", "GMC", "Hummer EV SUV", "2024", "~"),
  r("SUV", "EV", "Lincoln", "Nautilus (2025)", "2025", "~"),

  // --- Rivian / Lucid / Fisker / Scout ---
  r("SUV", "EV", "Rivian", "R1S (Gen 2)", "2025", "~"),
  r("Pickup", "EV", "Rivian", "R1T (Gen 2)", "2025", "~"),
  r("SUV", "EV", "Rivian", "R2", "2026", "~"),
  r("SUV", "EV", "Rivian", "R3", "2026", "~"),
  r("Sedan", "EV", "Lucid", "Air (2025 Refresh)", "2025", "~"),
  r("SUV", "EV", "Lucid", "Gravity", "2025", "~"),
  r("SUV", "EV", "Scout", "Traveler", "2026", "~"),
  r("Pickup", "EV", "Scout", "Terra", "2026", "~"),

  // --- Chinese exports & global ---
  r("SUV", "EV", "MG", "Cyberster", "2024", "~"),
  r("SUV", "EV", "MG", "S5 EV", "2025", "~"),
  r("Hatchback", "EV", "MG", "4 XPower", "2024", "~"),
  r("SUV", "EV", "MG", "ZS EV (2025 Refresh)", "2025", "~"),
  r("SUV", "EV", "GWM", "Ora 03 / Funky Cat", "2022", "~"),
  r("SUV", "PHEV", "GWM", "Tank 300 Hi4-T", "2024", "~"),
  r("SUV", "PHEV", "GWM", "Tank 500 Hi4-T", "2024", "~"),
  r("Pickup", "Diesel", "GWM", "Cannon Alpha", "2024", "~"),
  r("SUV", "EV", "Chery", "Omoda E5", "2024", "~"),
  r("SUV", "PHEV", "Chery", "Jaecoo J7 PHEV", "2024", "~"),
  r("SUV", "PHEV", "Chery", "Tiggo 8 Pro PHEV", "2024", "~"),
  r("SUV", "EV", "Geely", "EX5", "2024", "~"),
  r("Sedan", "EV", "Geely", "Galaxy E8", "2024", "~"),
  r("SUV", "EV", "Smart", "#3", "2023", "~"),
  r("SUV", "EV", "Smart", "#5", "2025", "~"),
  r("SUV", "EV", "Leapmotor", "C10", "2024", "~"),
  r("Hatchback", "EV", "Leapmotor", "T03", "2024", "~"),
  r("SUV", "EV", "Leapmotor", "B10", "2025", "~"),

  // --- Indian market (Tata / Mahindra / Maruti) ---
  r("SUV", "EV", "Tata", "Curvv EV", "2024", "~"),
  r("SUV", "EV", "Tata", "Harrier EV", "2025", "~"),
  r("SUV", "EV", "Tata", "Punch EV", "2024", "~"),
  r("SUV", "EV", "Tata", "Nexon EV (2024 Refresh)", "2024", "~"),
  r("Hatchback", "EV", "Tata", "Tiago EV", "2022", "~"),
  r("SUV", "EV", "Mahindra", "BE 6", "2024", "~"),
  r("SUV", "EV", "Mahindra", "XEV 9e", "2024", "~"),
  r("SUV", "Diesel", "Mahindra", "Thar Roxx", "2024", "~"),
  r("SUV", "Petrol", "Maruti Suzuki", "Grand Vitara (2024 Refresh)", "2024", "~"),
  r("SUV", "EV", "Maruti Suzuki", "e Vitara", "2025", "~"),

  // --- Malaysian market ---
  r("Sedan", "Petrol", "Proton", "S70 (2024)", "2024", "~"),
  r("SUV", "EV", "Proton", "e.MAS 7", "2024", "~"),
  r("SUV", "Petrol", "Proton", "X50 (2024 Refresh)", "2024", "~"),
  r("SUV", "Petrol", "Proton", "X90", "2023", "~"),
  r("SUV", "Petrol", "Perodua", "Ativa (2024)", "2024", "~"),
  r("Hatchback", "Petrol", "Perodua", "Axia (2023 Refresh)", "2023", "~"),
  r("MPV", "Petrol", "Perodua", "Alza (2022 Refresh)", "2022", "~"),
  r("Sedan", "Petrol", "Perodua", "Bezza (2025 Refresh)", "2025", "~"),

  // --- Motorcycles / Scooters latest ---
  r("Bike", "Petrol", "Honda", "CBR1000RR-R Fireblade SP (2024)", "2024", "~"),
  r("Bike", "Petrol", "Yamaha", "R1 (2025 Refresh)", "2025", "~"),
  r("Bike", "Petrol", "Yamaha", "MT-09 (2024)", "2024", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja ZX-4RR", "2024", "~"),
  r("Bike", "Petrol", "Kawasaki", "Ninja H2R (2024)", "2024", "~"),
  r("Bike", "Petrol", "Suzuki", "GSX-8R", "2024", "~"),
  r("Bike", "Petrol", "Ducati", "Panigale V4 (2025)", "2025", "~"),
  r("Bike", "Petrol", "Ducati", "Streetfighter V4 S (2025)", "2025", "~"),
  r("Bike", "Petrol", "BMW", "M 1000 RR (2025)", "2025", "~"),
  r("Bike", "Petrol", "BMW", "R 1300 GS", "2024", "~"),
  r("Bike", "Petrol", "KTM", "1390 Super Duke R Evo", "2024", "~"),
  r("Bike", "Petrol", "Triumph", "Speed 400", "2024", "~"),
  r("Bike", "Petrol", "Triumph", "Daytona 660", "2024", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Himalayan 450", "2024", "~"),
  r("Bike", "Petrol", "Royal Enfield", "Shotgun 650", "2024", "~"),
  r("Bike", "EV", "Harley-Davidson", "LiveWire S2 Mulholland", "2024", "~"),
  r("Bike", "EV", "Zero", "SR/F (2025)", "2025", "~"),
  r("Bike", "EV", "Damon", "HyperSport HS", "2025", "~"),
  r("Scooter", "EV", "Honda", "EM1 e:", "2024", "~"),
  r("Scooter", "EV", "Yamaha", "E01", "2024", "~"),
  r("Scooter", "EV", "Vespa", "Elettrica (2024)", "2024", "~"),
  r("Scooter", "EV", "Ola Electric", "S1 Pro Gen 2", "2024", "~"),
  r("Scooter", "EV", "Ather", "Rizta", "2024", "~"),
  r("Scooter", "EV", "TVS", "iQube (2024 Refresh)", "2024", "~"),
  r("Scooter", "EV", "Bajaj", "Chetak Premium 2025", "2025", "~"),

  // --- Commercial / Vans / Trucks latest ---
  r("Van", "EV", "Mercedes-Benz", "eSprinter (2024)", "2024", "~"),
  r("Van", "EV", "Ford", "E-Transit Custom", "2024", "~"),
  r("Van", "EV", "Volkswagen", "ID.Buzz Cargo", "2023", "~"),
  r("Van", "EV", "Renault", "Master E-Tech", "2024", "~"),
  r("Van", "EV", "Stellantis", "K0 Platform Vans (2024)", "2024", "~"),
  r("Truck", "EV", "Volvo Trucks", "FH Aero Electric", "2024", "~"),
  r("Truck", "EV", "Mercedes-Benz", "eActros 600", "2024", "~"),
  r("Truck", "Hydrogen", "Hyundai", "Xcient Fuel Cell (2025)", "2025", "~"),
  r("Truck", "EV", "Tesla", "Semi (Production)", "2024", "~"),
  r("Truck", "EV", "Renault Trucks", "E-Tech T", "2024", "~"),
  r("Bus", "EV", "BYD", "B12 e-Coach", "2024", "~"),
  r("Bus", "Hydrogen", "Solaris", "Urbino 18 Hydrogen", "2024", "~"),
  r("Bus", "EV", "Yutong", "E12 Pro", "2024", "~"),
];

export const VEHICLE_CATALOG: VehicleCatalogRow[] = [
  ...SEDAN,
  ...HATCHBACK,
  ...COUPE,
  ...CONVERTIBLE,
  ...WAGON,
  ...SUV,
  ...MPV,
  ...PICKUP,
  ...VAN,
  ...TRUCK,
  ...BUS,
  ...BIKE,
  ...SCOOTER,
  ...AUTO,
  ...KEI,
  ...BICYCLE,
  ...LATEST,
];

/** Convert a catalog row into the persistence shape used by the screen. */
export const catalogRowToValues = (
  row: VehicleCatalogRow,
): Record<string, string | number | boolean> => ({
  vehicleType: row.vehicleType,
  energyType: row.energyType,
  make: row.make,
  model: row.model,
  yearFrom: row.yearFrom,
  yearTo: row.yearTo,
  iconUri: "",
  status: true,
});
