-- ============================================================================
-- Migration 0017: seed countries / states / cities
-- ----------------------------------------------------------------------------
-- Replaces the in-app SEED_ENTRIES["country-states-cities"] block that used to
-- live in AdminDataContext. After this migration the app no longer carries the
-- baseline region list in AsyncStorage; reads come from Supabase only.
--
-- Idempotent: ON CONFLICT DO NOTHING. Run after 0016_regions_tables.sql.
-- ============================================================================

-- ---- Countries ------------------------------------------------------------
insert into public.countries (name, position) values
  ('Malaysia',         10),
  ('Singapore',        20),
  ('Thailand',         30),
  ('Indonesia',        40),
  ('Philippines',      50),
  ('Vietnam',          60),
  ('China',            70),
  ('Hong Kong',        80),
  ('Taiwan',           90),
  ('Japan',           100),
  ('South Korea',     110),
  ('India',           120),
  ('UAE',             130),
  ('Qatar',           140),
  ('Saudi Arabia',    150),
  ('Turkey',          160),
  ('United Kingdom',  170),
  ('France',          180),
  ('Germany',         190),
  ('Spain',           200),
  ('Italy',           210),
  ('Netherlands',     220),
  ('Switzerland',     230),
  ('United States',   240),
  ('Canada',          250),
  ('Mexico',          260),
  ('Brazil',          270),
  ('Argentina',       280),
  ('Australia',       290),
  ('New Zealand',     300),
  ('South Africa',    310),
  ('Egypt',           320),
  ('Morocco',         330),
  ('Kenya',           340),
  ('Nigeria',         350)
on conflict (name) do nothing;

-- ---- States ---------------------------------------------------------------
insert into public.states (country, name) values
  -- Malaysia
  ('Malaysia','Selangor'),
  ('Malaysia','Kuala Lumpur'),
  ('Malaysia','Putrajaya'),
  ('Malaysia','Penang'),
  ('Malaysia','Johor'),
  ('Malaysia','Perak'),
  ('Malaysia','Kedah'),
  ('Malaysia','Perlis'),
  ('Malaysia','Kelantan'),
  ('Malaysia','Terengganu'),
  ('Malaysia','Pahang'),
  ('Malaysia','Negeri Sembilan'),
  ('Malaysia','Malacca'),
  ('Malaysia','Sabah'),
  ('Malaysia','Sarawak'),
  ('Malaysia','Labuan'),
  -- Singapore
  ('Singapore','Singapore'),
  -- Thailand
  ('Thailand','Bangkok'),
  ('Thailand','Chiang Mai'),
  ('Thailand','Phuket'),
  ('Thailand','Krabi'),
  ('Thailand','Songkhla'),
  -- Indonesia
  ('Indonesia','Jakarta'),
  ('Indonesia','Bali'),
  ('Indonesia','East Java'),
  ('Indonesia','Yogyakarta'),
  ('Indonesia','North Sumatra'),
  -- Philippines
  ('Philippines','Metro Manila'),
  ('Philippines','Cebu'),
  ('Philippines','Davao del Sur'),
  -- Vietnam
  ('Vietnam','Ho Chi Minh'),
  ('Vietnam','Hanoi'),
  ('Vietnam','Da Nang'),
  -- China / HK / Taiwan
  ('China','Beijing'),
  ('China','Shanghai'),
  ('China','Guangdong'),
  ('Hong Kong','Hong Kong'),
  ('Taiwan','Taipei'),
  ('Taiwan','Taoyuan'),
  -- Japan / Korea
  ('Japan','Tokyo'),
  ('Japan','Osaka'),
  ('Japan','Kyoto'),
  ('South Korea','Seoul'),
  ('South Korea','Busan'),
  -- India
  ('India','Delhi'),
  ('India','Maharashtra'),
  ('India','Karnataka'),
  ('India','Tamil Nadu'),
  ('India','Telangana'),
  ('India','West Bengal'),
  -- Middle East
  ('UAE','Dubai'),
  ('UAE','Abu Dhabi'),
  ('Qatar','Doha'),
  ('Saudi Arabia','Riyadh'),
  ('Saudi Arabia','Mecca'),
  ('Turkey','Istanbul'),
  -- Europe
  ('United Kingdom','England'),
  ('United Kingdom','Scotland'),
  ('France','Ile-de-France'),
  ('France','PACA'),
  ('Germany','Bavaria'),
  ('Germany','Hesse'),
  ('Germany','Berlin'),
  ('Spain','Madrid'),
  ('Spain','Catalonia'),
  ('Italy','Lazio'),
  ('Italy','Lombardy'),
  ('Netherlands','North Holland'),
  ('Switzerland','Zurich'),
  -- Americas
  ('United States','New York'),
  ('United States','California'),
  ('United States','Illinois'),
  ('United States','Texas'),
  ('United States','Florida'),
  ('United States','Washington'),
  ('Canada','Ontario'),
  ('Canada','British Columbia'),
  ('Canada','Quebec'),
  ('Mexico','Mexico City'),
  ('Brazil','Sao Paulo'),
  ('Brazil','Rio de Janeiro'),
  ('Argentina','Buenos Aires'),
  -- Oceania
  ('Australia','New South Wales'),
  ('Australia','Victoria'),
  ('Australia','Queensland'),
  ('Australia','Western Australia'),
  ('New Zealand','Auckland'),
  ('New Zealand','Wellington'),
  -- Africa
  ('South Africa','Gauteng'),
  ('South Africa','Western Cape'),
  ('Egypt','Cairo'),
  ('Morocco','Casablanca-Settat'),
  ('Kenya','Nairobi'),
  ('Nigeria','Lagos')
on conflict (country, name) do nothing;

-- ---- Cities ---------------------------------------------------------------
insert into public.cities (country, state, name) values
  -- Malaysia
  ('Malaysia','Selangor','Petaling Jaya'),
  ('Malaysia','Selangor','Shah Alam'),
  ('Malaysia','Selangor','Subang Jaya'),
  ('Malaysia','Selangor','Klang'),
  ('Malaysia','Selangor','Kajang'),
  ('Malaysia','Selangor','Sepang'),
  ('Malaysia','Kuala Lumpur','Kuala Lumpur'),
  ('Malaysia','Kuala Lumpur','Cheras'),
  ('Malaysia','Kuala Lumpur','Setapak'),
  ('Malaysia','Putrajaya','Putrajaya'),
  ('Malaysia','Penang','George Town'),
  ('Malaysia','Penang','Bayan Lepas'),
  ('Malaysia','Penang','Butterworth'),
  ('Malaysia','Johor','Johor Bahru'),
  ('Malaysia','Johor','Iskandar Puteri'),
  ('Malaysia','Johor','Senai'),
  ('Malaysia','Johor','Batu Pahat'),
  ('Malaysia','Perak','Ipoh'),
  ('Malaysia','Perak','Taiping'),
  ('Malaysia','Kedah','Alor Setar'),
  ('Malaysia','Kedah','Sungai Petani'),
  ('Malaysia','Kedah','Langkawi'),
  ('Malaysia','Perlis','Kangar'),
  ('Malaysia','Kelantan','Kota Bharu'),
  ('Malaysia','Terengganu','Kuala Terengganu'),
  ('Malaysia','Pahang','Kuantan'),
  ('Malaysia','Pahang','Temerloh'),
  ('Malaysia','Pahang','Cameron Highlands'),
  ('Malaysia','Negeri Sembilan','Seremban'),
  ('Malaysia','Malacca','Malacca City'),
  ('Malaysia','Sabah','Kota Kinabalu'),
  ('Malaysia','Sabah','Sandakan'),
  ('Malaysia','Sabah','Tawau'),
  ('Malaysia','Sarawak','Kuching'),
  ('Malaysia','Sarawak','Miri'),
  ('Malaysia','Sarawak','Sibu'),
  ('Malaysia','Sarawak','Bintulu'),
  ('Malaysia','Labuan','Labuan'),
  -- Singapore
  ('Singapore','Singapore','Singapore'),
  ('Singapore','Singapore','Jurong'),
  ('Singapore','Singapore','Tampines'),
  -- Thailand
  ('Thailand','Bangkok','Bangkok'),
  ('Thailand','Chiang Mai','Chiang Mai'),
  ('Thailand','Phuket','Phuket'),
  ('Thailand','Krabi','Krabi'),
  ('Thailand','Songkhla','Hat Yai'),
  -- Indonesia
  ('Indonesia','Jakarta','Jakarta'),
  ('Indonesia','Bali','Denpasar'),
  ('Indonesia','Bali','Ubud'),
  ('Indonesia','East Java','Surabaya'),
  ('Indonesia','Yogyakarta','Yogyakarta'),
  ('Indonesia','North Sumatra','Medan'),
  -- Philippines
  ('Philippines','Metro Manila','Manila'),
  ('Philippines','Metro Manila','Quezon City'),
  ('Philippines','Cebu','Cebu City'),
  ('Philippines','Davao del Sur','Davao'),
  -- Vietnam
  ('Vietnam','Ho Chi Minh','Ho Chi Minh City'),
  ('Vietnam','Hanoi','Hanoi'),
  ('Vietnam','Da Nang','Da Nang'),
  -- China / HK / Taiwan
  ('China','Beijing','Beijing'),
  ('China','Shanghai','Shanghai'),
  ('China','Guangdong','Guangzhou'),
  ('China','Guangdong','Shenzhen'),
  ('Hong Kong','Hong Kong','Hong Kong'),
  ('Taiwan','Taipei','Taipei'),
  ('Taiwan','Taoyuan','Taoyuan'),
  -- Japan / Korea
  ('Japan','Tokyo','Tokyo'),
  ('Japan','Osaka','Osaka'),
  ('Japan','Kyoto','Kyoto'),
  ('South Korea','Seoul','Seoul'),
  ('South Korea','Busan','Busan'),
  -- India
  ('India','Delhi','New Delhi'),
  ('India','Maharashtra','Mumbai'),
  ('India','Maharashtra','Pune'),
  ('India','Karnataka','Bangalore'),
  ('India','Tamil Nadu','Chennai'),
  ('India','Telangana','Hyderabad'),
  ('India','West Bengal','Kolkata'),
  -- Middle East
  ('UAE','Dubai','Dubai'),
  ('UAE','Abu Dhabi','Abu Dhabi'),
  ('Qatar','Doha','Doha'),
  ('Saudi Arabia','Riyadh','Riyadh'),
  ('Saudi Arabia','Mecca','Jeddah'),
  ('Turkey','Istanbul','Istanbul'),
  -- Europe
  ('United Kingdom','England','London'),
  ('United Kingdom','England','Manchester'),
  ('United Kingdom','Scotland','Edinburgh'),
  ('France','Ile-de-France','Paris'),
  ('France','PACA','Nice'),
  ('Germany','Bavaria','Munich'),
  ('Germany','Hesse','Frankfurt'),
  ('Germany','Berlin','Berlin'),
  ('Spain','Madrid','Madrid'),
  ('Spain','Catalonia','Barcelona'),
  ('Italy','Lazio','Rome'),
  ('Italy','Lombardy','Milan'),
  ('Netherlands','North Holland','Amsterdam'),
  ('Switzerland','Zurich','Zurich'),
  -- Americas
  ('United States','New York','New York'),
  ('United States','California','Los Angeles'),
  ('United States','California','San Francisco'),
  ('United States','Illinois','Chicago'),
  ('United States','Texas','Dallas'),
  ('United States','Texas','Houston'),
  ('United States','Florida','Miami'),
  ('United States','Washington','Seattle'),
  ('Canada','Ontario','Toronto'),
  ('Canada','British Columbia','Vancouver'),
  ('Canada','Quebec','Montreal'),
  ('Mexico','Mexico City','Mexico City'),
  ('Brazil','Sao Paulo','Sao Paulo'),
  ('Brazil','Rio de Janeiro','Rio de Janeiro'),
  ('Argentina','Buenos Aires','Buenos Aires'),
  -- Oceania
  ('Australia','New South Wales','Sydney'),
  ('Australia','Victoria','Melbourne'),
  ('Australia','Queensland','Brisbane'),
  ('Australia','Western Australia','Perth'),
  ('New Zealand','Auckland','Auckland'),
  ('New Zealand','Wellington','Wellington'),
  -- Africa
  ('South Africa','Gauteng','Johannesburg'),
  ('South Africa','Western Cape','Cape Town'),
  ('Egypt','Cairo','Cairo'),
  ('Morocco','Casablanca-Settat','Casablanca'),
  ('Kenya','Nairobi','Nairobi'),
  ('Nigeria','Lagos','Lagos')
on conflict (country, state, name) do nothing;

-- ---- Suburbs --------------------------------------------------------------
-- Intentionally empty for the baseline. Add via the admin UI.
